program quipos;

uses
  windows,
  forms,
  classes,
  controls,
  sysutils,
  dialogs,
  uMain in 'uMain.pas' {frmmain},
  usaida in 'usaida.pas' {frmsaida},
  ucondpagto in 'ucondpagto.pas' {frmCondPagto},
  uempresa in 'uempresa.pas' {frmEmpresa},
  uFornecedor in 'uFornecedor.pas' {frmFornecedor},
  ulocalizar in 'ulocalizar.pas' {frmLocalizar},
  ucliente in 'ucliente.pas' {frmCliente},
  uDtmMain in 'uDtmMain.pas' {dtmmain: TDataModule},
  uEtapa in 'uEtapa.pas' {frmEtapa},
  uFuncionario in 'uFuncionario.pas' {frmFuncionario},
  ucontrato in 'ucontrato.pas' {frmContrato},
  uFaturamento in 'uFaturamento.pas' {frmFaturamento},
  uLocacao in 'uLocacao.pas' {frmlocacao},
  uFaturamentoTipo in 'uFaturamentoTipo.pas' {frmFaturamentoTipo},
  uacbr in 'uacbr.pas' {frmsetacbr},
  uveiculo in 'uveiculo.pas' {frmVeiculo},
  uRichEdit in 'uRichEdit.pas' {frmRichEdit},
  ucte in 'ucte.pas' {frmCTE},
  uuf in 'uuf.pas' {frmUF},
  uConstantes in 'uConstantes.pas',
  uitsaidaimportacao in 'uitsaidaimportacao.pas' {frmdlgitsaidaimportacao},
  urota in 'urota.pas' {frmrota},
  utarefa in 'utarefa.pas' {frmdlgtarefa},
  urpa in 'urpa.pas' {frmRPA},
  utransportadora in 'utransportadora.pas' {frmTransportadora},
  uctetransportadora in 'uctetransportadora.pas' {frmctetransportadora},
  utabela in 'utabela.pas' {frmTabela1},
  uprojeto in 'uprojeto.pas' {frmdlgProjeto},
  uagenda in 'uagenda.pas' {frmagenda},
  uitagenda in 'uitagenda.pas' {frmdlgitagenda},
  umetrologia in 'umetrologia.pas' {frmMetrologia},
  uEquipamento in 'uEquipamento.pas' {frmEquipamento},
  ueventoemail in 'ueventoemail.pas' {frmEventoEmail},
  upaciente in 'upaciente.pas' {frmPaciente},
  uprofissional in 'uprofissional.pas' {frmProfissional},
  ucontratonegociacao in 'ucontratonegociacao.pas' {frmdlgGerarNegociacaoContrato},
  uembarque in 'uembarque.pas' {frmEmbarque},
  uworkbox in 'uworkbox.pas' {frmWorkBox},
  uordserv in 'uordserv.pas' {frmOrdServ},
  utransporte in 'utransporte.pas' {frmtransporte},
  uGrupos in 'uGrupos.pas' {frmGrupos},
  umdfe in 'umdfe.pas' {frmmdfe},
  uimportacao in 'uimportacao.pas' {frmImportacao},
  ACBR.Status in 'ACBR\ACBR.Status.pas' {frmstacbr},
  ACBR.NfeReport in 'ACBR\ACBR.NfeReport.pas' {frmnfereport},
  ACBR.MdfeReport in 'ACBR\ACBR.MdfeReport.pas' {frmmdfereport},
  ACBR.EntradaImportarxml in 'ACBR\ACBR.EntradaImportarxml.pas' {frmentradaimportarxml},
  ACBR.CteReport in 'ACBR\ACBR.CteReport.pas' {frmctereport},
  ACBR.CartaCorrecao in 'ACBR\ACBR.CartaCorrecao.pas' {frmdlgcartacorrecao},
  ACBR.CartaCorrecaoCTE in 'ACBR\ACBR.CartaCorrecaoCTE.pas' {frmcartacorrecaocte},
  ACBR.NFSE in 'ACBR\ACBR.NFSE.pas',
  ACBR.Boleto in 'ACBR\ACBR.Boleto.pas',
  ACBR.NFEABR in 'ACBR\ACBR.NFEABR.pas',
  ACBR.NFE in 'ACBR\ACBR.NFE.pas',
  ACBR.ACBR in 'ACBR\ACBR.ACBR.pas',
  ACBR.CTEGerar in 'ACBR\ACBR.CTEGerar.pas',
  Aquisicao.Entrada in 'Aquisicao\Aquisicao.Entrada.pas' {frmentrada},
  Aquisicao.PedidoMaterial in 'Aquisicao\Aquisicao.PedidoMaterial.pas' {frmPedidoMaterial},
  Aquisicao.OrdCompra in 'Aquisicao\Aquisicao.OrdCompra.pas' {frmOrdCompra},
  classe.orcamentocopiar in 'classe\classe.orcamentocopiar.pas',
  Classe.CriterioReport in 'classe\Classe.CriterioReport.pas',
  Classe.CalculoPrestacao in 'classe\Classe.CalculoPrestacao.pas',
  Classe.ORM in 'classe\Classe.ORM.pas',
  Classe.DAO in 'classe\Classe.DAO.pas',
  Classe.Conection in 'classe\Classe.Conection.pas',
  Classe.ManagerAutpagto in 'classe\Classe.ManagerAutpagto.pas',
  Classe.Conexao in 'classe\Classe.Conexao.pas',
  Classe.ImpressaoMatricial in 'classe\Classe.ImpressaoMatricial.pas',
  Classe.ProdutoFGerarBaixaEstoqueSubProduto in 'classe\Classe.ProdutoFGerarBaixaEstoqueSubProduto.pas',
  Classe.Localizar in 'classe\Classe.Localizar.pas',
  Classe.GerarCustoMedioLivroProducao in 'classe\Classe.GerarCustoMedioLivroProducao.pas',
  Classe.Interna in 'classe\Classe.Interna.pas',
  Classe.Generics in 'classe\Classe.Generics.pas',
  Classe.DebitoAutomatico in 'classe\Classe.DebitoAutomatico.pas',
  classe.Versao in 'classe\classe.Versao.pas',
  classe.Registro in 'classe\classe.Registro.pas',
  classe.form in 'classe\classe.form.pas',
  classe.mensagem in 'classe\classe.mensagem.pas',
  Classe.Main in 'classe\Classe.Main.pas',
  classe.Caixafinanceiro in 'classe\classe.Caixafinanceiro.pas',
  classe.LivroFiscal in 'classe\classe.LivroFiscal.pas',
  classe.LivroFiscalDigital in 'classe\classe.LivroFiscalDigital.pas',
  classe.gerar in 'classe\classe.gerar.pas',
  classe.Registrainformacao in 'classe\classe.Registrainformacao.pas',
  classe.relatorio in 'classe\classe.relatorio.pas',
  classe.Endereco in 'classe\classe.Endereco.pas',
  classe.Executasql in 'classe\classe.Executasql.pas',
  classe.impressaoreport in 'classe\classe.impressaoreport.pas',
  classe.gerarautpagto in 'classe\classe.gerarautpagto.pas',
  classe.CopiarRegistro in 'classe\classe.CopiarRegistro.pas',
  classe.ColumnField in 'classe\classe.ColumnField.pas',
  classe.Calculopeso in 'classe\classe.Calculopeso.pas',
  classe.Etiqueta in 'classe\classe.Etiqueta.pas',
  classe.Aplicacao in 'classe\classe.Aplicacao.pas',
  classe.DifAliquota in 'classe\classe.DifAliquota.pas',
  classe.sintegra in 'classe\classe.sintegra.pas',
  classe.query in 'classe\classe.query.pas',
  classe.efdpiscofins in 'classe\classe.efdpiscofins.pas',
  classe.email in 'classe\classe.email.pas',
  classe.InstrucaoSQL in 'classe\classe.InstrucaoSQL.pas',
  Comercial.ConferenciaPedido in 'Comercial\Comercial.ConferenciaPedido.pas' {frmConferenciaPedido},
  Comercial.Pedido in 'Comercial\Comercial.Pedido.pas' {frmPedido},
  Comercial.Representante in 'Comercial\Comercial.Representante.pas' {frmRepresentante},
  Comercial.Orcamento in 'Comercial\Comercial.Orcamento.pas' {frmOrcamento},
  Comercial.PedidoBalcao in 'Comercial\Comercial.PedidoBalcao.pas' {frmPedidoBalcao},
  Consulta.Pedido in 'Consulta\Consulta.Pedido.pas' {frmConsultaPedido},
  Consulta.Representante in 'Consulta\Consulta.Representante.pas' {frmConsultaRepresentante},
  Consulta.Autpagto in 'Consulta\Consulta.Autpagto.pas' {frmConsultaAutpagto},
  Consulta.Cliente in 'Consulta\Consulta.Cliente.pas' {frmConsultaCliente},
  Consulta.Duplicata in 'Consulta\Consulta.Duplicata.pas' {frmConsultaDuplicata},
  Consulta.Entrada in 'Consulta\Consulta.Entrada.pas' {frmConsultaEntrada},
  Consulta.Movbancario in 'Consulta\Consulta.Movbancario.pas' {frmConsultaMovBancario},
  Consulta.Movto in 'Consulta\Consulta.Movto.pas' {frmConsultaMovto},
  Consulta.Produto in 'Consulta\Consulta.Produto.pas' {frmConsultaProduto},
  Consulta.Saida in 'Consulta\Consulta.Saida.pas' {frmConsultaSaida},
  Consulta.Cheque in 'Consulta\Consulta.Cheque.pas' {frmConsultaCheque},
  Consulta.Consulta in 'Consulta\Consulta.Consulta.pas' {frmconsulta},
  Dialogo.ExportarExcel in 'Dialogo\Dialogo.ExportarExcel.pas' {frmExporExcel},
  Dialogo.Versao in 'Dialogo\Dialogo.Versao.pas' {frmVersao},
  Dialogo.Login in 'Dialogo\Dialogo.Login.pas' {frmLogin},
  Dialogo.Progressbar in 'Dialogo\Dialogo.Progressbar.pas' {frmprogressbar},
  Dialogo.Release in 'Dialogo\Dialogo.Release.pas' {frmRelease},
  Dialogo.Negociacao in 'Dialogo\Dialogo.Negociacao.pas' {frmnegociacao},
  Dialogo.Para in 'Dialogo\Dialogo.Para.pas' {frmpara},
  Dialogo.MudarEtapa in 'Dialogo\Dialogo.MudarEtapa.pas' {frmmudaretapa},
  Dialogo.MarkupEntrada in 'Dialogo\Dialogo.MarkupEntrada.pas' {frmmarkupentrada},
  Dialogo.ProdutoInsercaoCdbarras in 'Dialogo\Dialogo.ProdutoInsercaoCdbarras.pas' {frmprodutoinsercaocdbarras},
  Dialogo.ExibirCampos in 'Dialogo\Dialogo.ExibirCampos.pas' {frmexibircampos},
  Dialogo.SelecionarEntrada in 'Dialogo\Dialogo.SelecionarEntrada.pas' {frmSelecionarEntrada},
  Dialogo.SetChangeTarefa in 'Dialogo\Dialogo.SetChangeTarefa.pas' {frmsetchangetarefa},
  Dialogo.SelecionarCertificado in 'Dialogo\Dialogo.SelecionarCertificado.pas' {frmSelecionarCertificado},
  Dialogo.Anotacao in 'Dialogo\Dialogo.Anotacao.pas' {frmAnotacao},
  Dialogo.DBMemo in 'Dialogo\Dialogo.DBMemo.pas' {frmdbMemo},
  Dialogo.AssinaturaDigital in 'Dialogo\Dialogo.AssinaturaDigital.pas' {frmAssinaturaDigital},
  Dialogo.Configuracao in 'Dialogo\Dialogo.Configuracao.pas' {frmConfiguracao},
  Dialogo.AnaliseCritica in 'Dialogo\Dialogo.AnaliseCritica.pas' {frmdlganalisecritica},
  Dialogo.Download in 'Dialogo\Dialogo.Download.pas' {frmdownload},
  Dialogo.DeclinarOrcamento in 'Dialogo\Dialogo.DeclinarOrcamento.pas' {frmdlgdeclinarorcamento},
  Dialogo.LoteSerie in 'Dialogo\Dialogo.LoteSerie.pas' {frmloteserie},
  Dialogo.GerarOrdCompra in 'Dialogo\Dialogo.GerarOrdCompra.pas' {frmGerarOrdCompra},
  Dialogo.FiltrarOrdServ in 'Dialogo\Dialogo.FiltrarOrdServ.pas' {frmfiltrarOrdServ},
  Dialogo.GerarDevolucao in 'Dialogo\Dialogo.GerarDevolucao.pas' {frmGerarDevolucao},
  Dialogo.GerarCompra in 'Dialogo\Dialogo.GerarCompra.pas' {frmgerarCompra},
  Dialogo.Gerarpedido in 'Dialogo\Dialogo.Gerarpedido.pas' {frmdlgGerarPedido},
  Dialogo.FiltrarTarefa in 'Dialogo\Dialogo.FiltrarTarefa.pas' {frmFiltrarTarefa},
  Dialogo.FiltrarProjeto in 'Dialogo\Dialogo.FiltrarProjeto.pas' {frmFiltrarProjeto},
  Dialogo.GerarSaida in 'Dialogo\Dialogo.GerarSaida.pas' {frmdlgGerarSaida},
  Dialogo.TransferirAdntcliente in 'Dialogo\Dialogo.TransferirAdntcliente.pas' {frmdlgtransferiradntcliente},
  Dialogo.AplicarConfiguracaoGrupo in 'Dialogo\Dialogo.AplicarConfiguracaoGrupo.pas' {frmdlgaplicarconfiguracaogrupo},
  Dialogo.InfNumIntervencao in 'Dialogo\Dialogo.InfNumIntervencao.pas' {frmdlginfNumIntervencao},
  Dialogo.RichEdit in 'Dialogo\Dialogo.RichEdit.pas' {frmdlgrichedit},
  Dialogo.XMLToTreeview in 'Dialogo\Dialogo.XMLToTreeview.pas' {frmdlgxmltotreeview},
  Dialogo.InutilizarNFE in 'Dialogo\Dialogo.InutilizarNFE.pas' {frmdlginutilizarnfe},
  Dialogo.AprovarConciliado in 'Dialogo\Dialogo.AprovarConciliado.pas' {frmdlgaprovarconciliado},
  Dialogo.DataBalanco in 'Dialogo\Dialogo.DataBalanco.pas' {frmdlgdatabalanco},
  Dialogo.Selecionar in 'Dialogo\Dialogo.Selecionar.pas' {frmdlgselecionar},
  Dialogo.CalculoPeso in 'Dialogo\Dialogo.CalculoPeso.pas' {frmcalculopeso},
  Dialogo.FaturamentoProduto in 'Dialogo\Dialogo.FaturamentoProduto.pas' {frmdlgfaturamentoproduto},
  Dialogo.AvaliacaoIQF in 'Dialogo\Dialogo.AvaliacaoIQF.pas' {frmdlgavaliacaoiqf},
  Dialogo.EscolhePedido in 'Dialogo\Dialogo.EscolhePedido.pas' {frmdlgEscolhePedido},
  Dialogo.DesenhoOrcamento in 'Dialogo\Dialogo.DesenhoOrcamento.pas' {frmdlgdesenhoorcamento},
  Dialogo.GerarMovto in 'Dialogo\Dialogo.GerarMovto.pas' {frmdlgGerarMovto},
  Dialogo.GerarDevolucaoSaida in 'Dialogo\Dialogo.GerarDevolucaoSaida.pas' {frmdglgerardevolucaosaida},
  Dialogo.InutilizarCTE in 'Dialogo\Dialogo.InutilizarCTE.pas' {frmdlginutilizarcte},
  Dialogo.SequenciaImpressao in 'Dialogo\Dialogo.SequenciaImpressao.pas' {frmdlgsequenciaimpressao},
  Dialogo.Detalhe.Orcamento in 'Dialogo\Dialogo.Detalhe.Orcamento.pas' {frmdlgdetalheorcamento},
  Dialogo.EntradaProduto in 'Dialogo\Dialogo.EntradaProduto.pas' {frmdlgentradaproduto},
  Dialogo.ChaveUso in 'Dialogo\Dialogo.ChaveUso.pas' {frmdlgchaveuso},
  Dialogo.MetodoProcesso in 'Dialogo\Dialogo.MetodoProcesso.pas' {frmdlgmetodoprocesso},
  Dialogo.SelecionarLista in 'Dialogo\Dialogo.SelecionarLista.pas' {frmdlgselecionarlista},
  Dialogo.SetAvisoTarefa in 'Dialogo\Dialogo.SetAvisoTarefa.pas' {frmdlgsetavisotarefa},
  Dialogo.AvisoTarefa in 'Dialogo\Dialogo.AvisoTarefa.pas' {frmdlgavisotarefa},
  Dialogo.LocacaoDevolucao in 'Dialogo\Dialogo.LocacaoDevolucao.pas' {frmdlglocacaodevolucao},
  Dialogo.Tabela in 'Dialogo\Dialogo.Tabela.pas' {frmdlttabela},
  Dialogo.Arquivo in 'Dialogo\Dialogo.Arquivo.pas' {frmdlgarquivo},
  Dialogo.Apontamento in 'Dialogo\Dialogo.Apontamento.pas' {frmdlgapontamento},
  Dialogo.Etiqueta in 'Dialogo\Dialogo.Etiqueta.pas' {frmdlgetiqueta},
  Dialogo.Lista in 'Dialogo\Dialogo.Lista.pas' {frmdlglista},
  Dialogo.TransferenciaBancaria in 'Dialogo\Dialogo.TransferenciaBancaria.pas' {frmdlgtransferenciabancaria},
  Dialogo.GerarAdiantamento in 'Dialogo\Dialogo.GerarAdiantamento.pas' {frmdlgAdntcliente},
  Dialogo.GerarMovimentacao in 'Dialogo\Dialogo.GerarMovimentacao.pas' {frmdlgDespesa},
  Dialogo.ClienteFinanceiro in 'Dialogo\Dialogo.ClienteFinanceiro.pas' {frmdlgclientefinanceiro},
  Dialogo.DuplicataCliente in 'Dialogo\Dialogo.DuplicataCliente.pas' {frmdlgduplicatacliente},
  Dialogo.HPedidoEtapa in 'Dialogo\Dialogo.HPedidoEtapa.pas' {frmdlghpedidoetapa},
  Dialogo.Justificativa in 'Dialogo\Dialogo.Justificativa.pas' {frmdlgjustificativa},
  Dialogo.OrdproducaoPesagem in 'Dialogo\Dialogo.OrdproducaoPesagem.pas' {frmdlgordprodcaopesagem},
  Dialogo.MapaProducaoProduto in 'Dialogo\Dialogo.MapaProducaoProduto.pas' {frmdlgmapaproducaoproduto},
  Dialogo.Tipo in 'Dialogo\Dialogo.Tipo.pas' {frmdlgTipo},
  Dialogo.CalculoPrestacao in 'Dialogo\Dialogo.CalculoPrestacao.pas' {frmdlgCalculoPrestacao},
  Dialogo.OrdcompraAprovacao in 'Dialogo\Dialogo.OrdcompraAprovacao.pas' {frmdlgOrdcompraAprovacao},
  Dialogo.Gerarprodutomensalidade in 'Dialogo\Dialogo.Gerarprodutomensalidade.pas' {frmfaturamentodlggerarprodutomensalidade},
  Estoque.Movto in 'Estoque\Estoque.Movto.pas' {frmmovto},
  Estoque.Grupo in 'Estoque\Estoque.Grupo.pas' {frmgrupo},
  Estoque.Rim in 'Estoque\Estoque.Rim.pas' {frmrim},
  Estoque.Baixa in 'Estoque\Estoque.Baixa.pas' {frmBaixaEstoque},
  Estoque.Dialogo.BaixaRequisicao in 'Estoque\Estoque.Dialogo.BaixaRequisicao.pas' {frmBaixaRequisicao},
  Estoque.Produto in 'Estoque\Estoque.Produto.pas' {frmProduto},
  Estoque.grade in 'Estoque\Estoque.grade.pas' {frmgrade},
  Exportacao.SaidaAlterdataSACA in 'Exportacao\Exportacao.SaidaAlterdataSACA.pas',
  Exportacao.Datasul.Duplicata in 'Exportacao\Datasul\Exportacao.Datasul.Duplicata.pas',
  Exportacao.Datasul.cte in 'Exportacao\Datasul\Exportacao.Datasul.cte.pas',
  Exportacao.Datasul.contabil in 'Exportacao\Datasul\Exportacao.Datasul.contabil.pas',
  Exportacao.Datasul.Autpagto in 'Exportacao\Datasul\Exportacao.Datasul.Autpagto.pas',
  Exportacao.Datasul.Movto in 'Exportacao\Datasul\Exportacao.Datasul.Movto.pas',
  Financeiro.AutpagtoParcelamento in 'Financeiro\Financeiro.AutpagtoParcelamento.pas' {frmdlgGerarParcelamentoAutpagto},
  Financeiro.Adntcliente in 'Financeiro\Financeiro.Adntcliente.pas' {frmAdntCliente},
  Financeiro.Adntfornecedor in 'Financeiro\Financeiro.Adntfornecedor.pas' {frmAdntFornecedor},
  Financeiro.Autpagto in 'Financeiro\Financeiro.Autpagto.pas' {frmAutPagto},
  Financeiro.Duplicata in 'Financeiro\Financeiro.Duplicata.pas' {frmDuplicata},
  Financeiro.plcontarateio in 'Financeiro\Financeiro.plcontarateio.pas' {frmplcontarateio},
  Financeiro.Cheque in 'Financeiro\Financeiro.Cheque.pas' {frmcheque},
  Financeiro.Conta in 'Financeiro\Financeiro.Conta.pas' {frmConta},
  Financeiro.DuplicataParcelamento in 'Financeiro\Financeiro.DuplicataParcelamento.pas' {frmdlgGerarParcelamentoDuplicata},
  Financeiro.RateioPlconta in 'Financeiro\Financeiro.RateioPlconta.pas' {frmRateioPlConta},
  Financeiro.RateioCntcusto in 'Financeiro\Financeiro.RateioCntcusto.pas' {frmRateioCntcusto},
  Financeiro.Movbancario in 'Financeiro\Financeiro.Movbancario.pas' {frmmovbancario},
  Financeiro.YMOFXReader in 'Financeiro\Financeiro.YMOFXReader.pas',
  Financeiro.Caixafinanceiro in 'Financeiro\Financeiro.Caixafinanceiro.pas' {frmcaixafinanceiro},
  Financeiro.Parcelamento in 'Financeiro\Financeiro.Parcelamento.pas' {frmparcelamento},
  Financeiro.Cobranca in 'Financeiro\Financeiro.Cobranca.pas' {frmCobranca},
  Financeiro.Plconta in 'Financeiro\Financeiro.Plconta.pas' {frmplconta},
  Financeiro.baixa in 'Financeiro\Financeiro.baixa.pas' {frmbaixa},
  Fiscal.Livro in 'Fiscal\Fiscal.Livro.pas' {frmlivro},
  Fiscal.Regrast in 'Fiscal\Fiscal.Regrast.pas' {frmRegrast},
  Fiscal.Cfop in 'Fiscal\Fiscal.Cfop.pas' {frmcfop},
  Fiscal.AtivoPisCofins in 'Fiscal\Fiscal.AtivoPisCofins.pas' {frmativopiscofins},
  Fiscal.Livrop3 in 'Fiscal\Fiscal.Livrop3.pas' {frmlivroP3},
  Gerenciador.Cobranca in 'Gerenciador\Gerenciador.Cobranca.pas' {frmManagerDuplicata},
  Gerenciador.Financeiro in 'Gerenciador\Gerenciador.Financeiro.pas' {frmManagerAutPagto},
  Gerenciador.Usuario in 'Gerenciador\Gerenciador.Usuario.pas' {frmManagerUser},
  Gerenciador.Pedido in 'Gerenciador\Gerenciador.Pedido.pas' {frmmanagerpedido},
  Geerenciador.Produto in 'Gerenciador\Geerenciador.Produto.pas' {frmManagerproduto},
  Gerenciador.Tarefa in 'Gerenciador\Gerenciador.Tarefa.pas' {frmmanagertarefa},
  Gerenciador.Gerenciador in 'Gerenciador\Gerenciador.Gerenciador.pas' {frmManager},
  Gerenciador.Ordproducao in 'Gerenciador\Gerenciador.Ordproducao.pas' {frmmanagerordproducao},
  Importacao.CTE in 'Importacao\Importacao.CTE.pas',
  Importacao.Inventario in 'Importacao\Importacao.Inventario.pas',
  Importacao.DOVerleih in 'Importacao\Importacao.DOVerleih.pas',
  Importacao.Senior in 'Importacao\Importacao.Senior.pas',
  Importacao.XML in 'Importacao\Importacao.XML.pas',
  Importacao.Gesoft in 'Importacao\Importacao.Gesoft.pas',
  Importacao.Excel in 'Importacao\Importacao.Excel.pas',
  Importacao.dados in 'Importacao\Importacao.dados.pas',
  Importacao.cliente in 'Importacao\Importacao.cliente.pas',
  Importacao.Fornecedor in 'Importacao\Importacao.Fornecedor.pas',
  Importacao.Transportadora in 'Importacao\Importacao.Transportadora.pas',
  Importacao.IPonto in 'Importacao\Importacao.IPonto.pas',
  Impressao.Report in 'Impressao\Impressao.Report.pas' {frmReport},
  Impressao.Rotina.FastFunc in 'Impressao\Impressao.Rotina.FastFunc.pas',
  Impressao.ReportUser in 'Impressao\Impressao.ReportUser.pas' {frmReportUser},
  Impressao.MenuRelatorio in 'Impressao\Impressao.MenuRelatorio.pas' {DTModuleMenuRelat: TDataModule},
  Impressao.ReportDesigner in 'Impressao\Impressao.ReportDesigner.pas' {frmreportdesigner},
  Impressao.EstoqueCompleto in 'Impressao\Impressao.EstoqueCompleto.pas' {frmestoquecompleto},
  Impressao.ReferenciaCruzada in 'Impressao\Impressao.ReferenciaCruzada.pas' {frmreferenciacruzada},
  Impressao.ProdutoEstoqueDiario in 'Impressao\Impressao.ProdutoEstoqueDiario.pas' {frmconsultaProdutoImprimirEstoquediario},
  Impressao.LivroProducao in 'Impressao\Impressao.LivroProducao.pas' {frmLivroProducaoImprimir},
  Impressao.OrdservOrcamentoAvulso in 'Impressao\Impressao.OrdservOrcamentoAvulso.pas',
  Impressao.OrdservOrcamentoContrato in 'Impressao\Impressao.OrdservOrcamentoContrato.pas',
  Impressao.OrdservWordEntregaSemComprovante in 'Impressao\Impressao.OrdservWordEntregaSemComprovante.pas',
  Impressao.AdntclienteFichaSaldo in 'Impressao\Impressao.AdntclienteFichaSaldo.pas',
  Impressao.AdntclienteSaldo in 'Impressao\Impressao.AdntclienteSaldo.pas',
  Impressao.AdntclienteSaldoDiario in 'Impressao\Impressao.AdntclienteSaldoDiario.pas',
  Impressao.CntcustoConsumoSemestral in 'Impressao\Impressao.CntcustoConsumoSemestral.pas',
  Impressao.AcompanhamentoVenda in 'Impressao\Impressao.AcompanhamentoVenda.pas',
  Impressao.CorridaCertificado in 'Impressao\Impressao.CorridaCertificado.pas',
  Impressao.ExtratoConta in 'Impressao\Impressao.ExtratoConta.pas',
  Impressao.RelatorioPadrao in 'Impressao\Impressao.RelatorioPadrao.pas',
  Impressao.SinteticoAutpagtoCntcusto in 'Impressao\Impressao.SinteticoAutpagtoCntcusto.pas',
  Impressao.FluxoCaixa in 'Impressao\Impressao.FluxoCaixa.pas',
  Impressao.FluxoCaixaRealizado in 'Impressao\Impressao.FluxoCaixaRealizado.pas',
  Impressao.DREAnalitico075 in 'Impressao\Impressao.DREAnalitico075.pas',
  Impressao.Balancete076 in 'Impressao\Impressao.Balancete076.pas',
  Impressao.DRE077 in 'Impressao\Impressao.DRE077.pas',
  Impressao.DREAnalitico078 in 'Impressao\Impressao.DREAnalitico078.pas',
  Impressao.Balancete079 in 'Impressao\Impressao.Balancete079.pas',
  Impressao.Balancete080 in 'Impressao\Impressao.Balancete080.pas',
  Impressao.DREAnalitico082 in 'Impressao\Impressao.DREAnalitico082.pas',
  Impressao.DRE081 in 'Impressao\Impressao.DRE081.pas',
  Impressao.OrdproducaoPesagem in 'Impressao\Impressao.OrdproducaoPesagem.pas',
  Impressao.FuncionarioCestaBasica in 'Impressao\Impressao.FuncionarioCestaBasica.pas',
  Impressao.MapaFreteMensal in 'Impressao\Impressao.MapaFreteMensal.pas',
  Impressao.GraticoTpparada in 'Impressao\Impressao.GraticoTpparada.pas',
  Impressao.GraficoParetoTpparada in 'Impressao\Impressao.GraficoParetoTpparada.pas',
  Impressao.PedidoAtendimento in 'Impressao\Impressao.PedidoAtendimento.pas',
  Impressao.ConsultaProdutoConsumo in 'Impressao\Impressao.ConsultaProdutoConsumo.pas',
  Impressao.DRE074 in 'Impressao\Impressao.DRE074.pas',
  Impressao.Fatura643 in 'Impressao\Impressao.Fatura643.pas',
  Impressao.PedidoMaterial in 'Impressao\Impressao.PedidoMaterial.pas',
  Impressao.MovimentacaoFinanceira in 'Impressao\Impressao.MovimentacaoFinanceira.pas',
  Impressao.InventarioEstoque in 'Impressao\Impressao.InventarioEstoque.pas',
  Impressao.ProdutoFichaMovimentacao in 'Impressao\Impressao.ProdutoFichaMovimentacao.pas' {frmconsultaProdutoImprimirFichaMovimentacao},
  Impressao.ProdutoMovimentoAnalitico in 'Impressao\Impressao.ProdutoMovimentoAnalitico.pas' {frmconsultaProdutoImprimirMovimentoAnalitico},
  Impressao.ProdutoFichaMovimentacaoterceiro in 'Impressao\Impressao.ProdutoFichaMovimentacaoterceiro.pas' {frmconsultaProdutoImprimirFichaMovimentacao1},
  Impressao.SaidaFreteMensaluf in 'Impressao\Impressao.SaidaFreteMensaluf.pas' {frmconsultasaidaImprimirFreteMensaluf},
  Impressao.SaidaReferenciaCruzada in 'Impressao\Impressao.SaidaReferenciaCruzada.pas' {frmconsultasaidareferenciacruzada},
  Impressao.SaidaMensalProdutoPM in 'Impressao\Impressao.SaidaMensalProdutoPM.pas' {frmconsultasaidaImprimirMensalProdutoPM},
  Impressao.SaidaMensalProdutoPP in 'Impressao\Impressao.SaidaMensalProdutoPP.pas' {frmconsultasaidaImprimirMensalProdutoPP},
  Localizar.Equipamento in 'Localizar\Localizar.Equipamento.pas' {frmLocalizarEquipamento},
  Localizar.Movbancario in 'Localizar\Localizar.Movbancario.pas' {frmLocalizarMovBancario},
  Localizar.Pedido in 'Localizar\Localizar.Pedido.pas' {frmLocalizarPedido},
  Localizar.Cliente in 'Localizar\Localizar.Cliente.pas' {frmLocalizarcliente},
  Localizar.Saida in 'Localizar\Localizar.Saida.pas' {frmLocalizarSaida},
  Localizar.Transportadora in 'Localizar\Localizar.Transportadora.pas' {frmLocalizarTransportadora},
  Localizar.Produto in 'Localizar\Localizar.Produto.pas' {frmLocalizarProduto},
  Localizar.Cheque in 'Localizar\Localizar.Cheque.pas' {frmLocalizarCheque},
  Localizar.Contrato in 'Localizar\Localizar.Contrato.pas' {frmLocalizarContrato},
  Localizar.Fornecedor in 'Localizar\Localizar.Fornecedor.pas' {frmLocalizarFornecedor},
  Localizar.AdntFornecedor in 'Localizar\Localizar.AdntFornecedor.pas' {frmLocalizarAdntFornecedor},
  Localizar.AutPagto in 'Localizar\Localizar.AutPagto.pas' {frmLocalizarAutPagto},
  Localizar.Entrada in 'Localizar\Localizar.Entrada.pas' {frmLocalizarEntrada},
  Localizar.Faturamento in 'Localizar\Localizar.Faturamento.pas' {frmLocalizarFaturamento},
  Localizar.AdntCliente in 'Localizar\Localizar.AdntCliente.pas' {frmLocalizarAdntCliente},
  Localizar.Rim in 'Localizar\Localizar.Rim.pas' {frmLocalizarRIM},
  Localizar.Funcionario in 'Localizar\Localizar.Funcionario.pas' {frmLocalizarFuncionario},
  Localizar.Locacao in 'Localizar\Localizar.Locacao.pas' {frmLocalizarLocacao},
  Localizar.Transporte in 'Localizar\Localizar.Transporte.pas' {frmLocalizartransporte},
  Localizar.Ordcompra in 'Localizar\Localizar.Ordcompra.pas' {frmLocalizarOrdCompra},
  Localizar.Movto in 'Localizar\Localizar.Movto.pas' {frmLocalizarMovto},
  Localizar.Cobranca in 'Localizar\Localizar.Cobranca.pas' {frmlocalizarcobranca},
  Localizar.Corridaquimica in 'Localizar\Localizar.Corridaquimica.pas' {frmLocalizarCorridaquimica},
  Localizar.Cte in 'Localizar\Localizar.Cte.pas' {frmLocalizarCTE},
  Localizar.Veiculo in 'Localizar\Localizar.Veiculo.pas' {frmLocalizarVeiculo},
  Localizar.Ordproducao in 'Localizar\Localizar.Ordproducao.pas' {frmLocalizarOrdProducao},
  Localizar.Rpa in 'Localizar\Localizar.Rpa.pas' {frmLocalizarRPA},
  Localizar.Ativopiscofins in 'Localizar\Localizar.Ativopiscofins.pas' {frmLocalizarAtivoPISCOFINS},
  Localizar.Itagenda in 'Localizar\Localizar.Itagenda.pas' {frmLocalizaritagenda},
  Localizar.MDFE in 'Localizar\Localizar.MDFE.pas' {frmLocalizarMDFE},
  Localizar.ConferenciaPedido in 'Localizar\Localizar.ConferenciaPedido.pas' {frmLocalizarConferenciaPedido},
  Localizar.Metrologia in 'Localizar\Localizar.Metrologia.pas' {frmLocalizarMetrologia},
  Localizar.Formulacao in 'Localizar\Localizar.Formulacao.pas' {frmLocalizarformulacao},
  Localizar.Duplicata in 'Localizar\Localizar.Duplicata.pas' {frmLocalizarduplicata},
  Localizar.Ordserv in 'Localizar\Localizar.Ordserv.pas' {frmLocalizarOrdserv},
  Localizar.PedidoMaterial in 'Localizar\Localizar.PedidoMaterial.pas' {frmLocalizarPedidoMaterial},
  Localizar.RequisicaoProducao in 'Localizar\Localizar.RequisicaoProducao.pas' {frmLocalizarRequisicaoProducao},
  Localizar.Paciente in 'Localizar\Localizar.Paciente.pas' {frmLocalizarPaciente},
  Localizar.RhOcorrencia in 'Localizar\Localizar.RhOcorrencia.pas' {frmLocalizarRHOcorrencia},
  localizar.negociacao in 'Localizar\localizar.negociacao.pas' {frmLocalizarnegociacao},
  Localizar.Parada in 'Localizar\Localizar.Parada.pas' {frmLocalizarParada},
  Localizar.Embarque in 'Localizar\Localizar.Embarque.pas' {frmLocalizarEmbarque},
  Localizar.ApontamentoManual in 'Localizar\Localizar.ApontamentoManual.pas' {frmLocalizarApontamentoManual},
  Localizar.Treinamento in 'Localizar\Localizar.Treinamento.pas' {frmLocalizarTreinamento},
  Localizar.DespesaConvenio in 'Localizar\Localizar.DespesaConvenio.pas' {frmLocalizardespesaconvenio},
  Localizar.Parcelamento in 'Localizar\Localizar.Parcelamento.pas' {frmLocalizarparcelamento},
  Localizar.Livrop3 in 'Localizar\Localizar.Livrop3.pas' {frmLocalizarlp1a},
  Localizar.Livro in 'Localizar\Localizar.Livro.pas' {frmLocalizarLivro},
  Localizar.Orcamento in 'Localizar\Localizar.Orcamento.pas' {frmLocalizarOrcamento},
  Model.Conexao.Interfaces in 'Model\conexao\Model.Conexao.Interfaces.pas',
  Model.Conexao.Firedac in 'Model\conexao\Model.Conexao.Firedac.pas',
  Novo.Paciente in 'Novo\Novo.Paciente.pas' {frmNovoPaciente},
  Novo.Produto in 'Novo\Novo.Produto.pas' {frmNovoProduto},
  Novo.Fornecedor in 'Novo\Novo.Fornecedor.pas' {frmNovoFornecedor},
  Novo.Equipamento in 'Novo\Novo.Equipamento.pas' {frmNovoEquipamento},
  Novo.Cliente in 'Novo\Novo.Cliente.pas' {frmNovoCliente},
  Novo.Tabela in 'Novo\Novo.Tabela.pas' {frmNovoTabela},
  Novo.Transportadora in 'Novo\Novo.Transportadora.pas' {frmNovoTransportadora},
  Novo.Mensagem in 'Novo\Novo.Mensagem.pas' {frmNovaMensagem},
  ORM.Requisicaoproducao in 'ORM\ORM.Requisicaoproducao.pas',
  ORM.DocFiscalICMS in 'ORM\ORM.DocFiscalICMS.pas',
  ORM.Funcionario in 'ORM\ORM.Funcionario.pas',
  ORM.Representante in 'ORM\ORM.Representante.pas',
  ORM.locacao in 'ORM\ORM.locacao.pas',
  ORM.ordcompra in 'ORM\ORM.ordcompra.pas',
  ORM.Orcamento in 'ORM\ORM.Orcamento.pas',
  ORM.Movto in 'ORM\ORM.Movto.pas',
  ORM.rim in 'ORM\ORM.rim.pas',
  ORM.Ordproducao in 'ORM\ORM.Ordproducao.pas',
  ORM.CTE in 'ORM\ORM.CTE.pas',
  ORM.Contrato in 'ORM\ORM.Contrato.pas',
  ORM.Tarefa in 'ORM\ORM.Tarefa.pas',
  ORM.Tabela in 'ORM\ORM.Tabela.pas',
  ORM.Mdfe in 'ORM\ORM.Mdfe.pas',
  ORM.Regrast in 'ORM\ORM.Regrast.pas',
  ORM.rota in 'ORM\ORM.rota.pas',
  ORM.Embarque in 'ORM\ORM.Embarque.pas',
  ORM.Apontamento in 'ORM\ORM.Apontamento.pas',
  ORM.Autpagto in 'ORM\ORM.Autpagto.pas',
  ORM.PontoTrabalho in 'ORM\ORM.PontoTrabalho.pas',
  ORM.Eventoemail in 'ORM\ORM.Eventoemail.pas',
  ORM.Paciente in 'ORM\ORM.Paciente.pas',
  ORM.Serie in 'ORM\ORM.Serie.pas',
  ORM.ApontamentoManual in 'ORM\ORM.ApontamentoManual.pas',
  ORM.Participante in 'ORM\ORM.Participante.pas',
  ORM.Parcelamento in 'ORM\ORM.Parcelamento.pas',
  ORM.Livroproducao in 'ORM\ORM.Livroproducao.pas',
  ORM.Importacao in 'ORM\ORM.Importacao.pas',
  ORM.ItSaidaLote in 'ORM\ORM.ItSaidaLote.pas',
  ORM.SaidaInutilizacao in 'ORM\ORM.SaidaInutilizacao.pas',
  ORM.CartaCorrecao in 'ORM\ORM.CartaCorrecao.pas',
  ORM.AdicaoImportacao in 'ORM\ORM.AdicaoImportacao.pas',
  ORM.ItSaidaImportacao in 'ORM\ORM.ItSaidaImportacao.pas',
  ORM.SaidaReferenciada in 'ORM\ORM.SaidaReferenciada.pas',
  ORM.Itsaidafretesub in 'ORM\ORM.Itsaidafretesub.pas',
  ORM.TpSaida in 'ORM\ORM.TpSaida.pas',
  ORM.Empresa in 'ORM\ORM.Empresa.pas',
  ORM.Movbancario in 'ORM\ORM.Movbancario.pas',
  ORM.Usuario in 'ORM\ORM.Usuario.pas',
  ORM.Produto in 'ORM\ORM.Produto.pas',
  ORM.Cliente in 'ORM\ORM.Cliente.pas',
  ORM.Faturamento in 'ORM\ORM.Faturamento.pas',
  ORM.Adntcliente in 'ORM\ORM.Adntcliente.pas',
  ORM.Cobranca in 'ORM\ORM.Cobranca.pas',
  ORM.Pagtocomissao in 'ORM\ORM.Pagtocomissao.pas',
  ORM.Etapa in 'ORM\ORM.Etapa.pas',
  ORM.duplicata in 'ORM\ORM.duplicata.pas',
  ORM.OrdServ in 'ORM\ORM.OrdServ.pas',
  ORM.Equipamento in 'ORM\ORM.Equipamento.pas',
  ORM.Conta in 'ORM\ORM.Conta.pas',
  ORM.PedidoMaterial in 'ORM\ORM.PedidoMaterial.pas',
  ORM.Fornecedor in 'ORM\ORM.Fornecedor.pas',
  ORM.tabirpf in 'ORM\ORM.tabirpf.pas',
  ORM.Entrada in 'ORM\ORM.Entrada.pas',
  ORM.saida in 'ORM\ORM.saida.pas',
  ORM.Transportadora in 'ORM\ORM.Transportadora.pas',
  ORM.Pedido in 'ORM\ORM.Pedido.pas',
  ORM.rpa in 'ORM\ORM.rpa.pas',
  ORM.ITSaida in 'ORM\ORM.ITSaida.pas',
  ORM.Report in 'ORM\ORM.Report.pas',
  ORM.Turma in 'ORM\ORM.Turma.pas',
  ORM.UF in 'ORM\ORM.UF.pas',
  ORM.Municipio in 'ORM\ORM.Municipio.pas',
  ORM.Cest in 'ORM\ORM.Cest.pas',
  ORM.TpAprovacao in 'ORM\ORM.TpAprovacao.pas',
  ORM.Grupos in 'ORM\ORM.Grupos.pas',
  ORM.ReportUser in 'ORM\ORM.ReportUser.pas',
  ORM.Formulacao in 'ORM\ORM.Formulacao.pas',
  ORM.TpCorrecao in 'ORM\ORM.TpCorrecao.pas',
  ORM.CFOP in 'ORM\ORM.CFOP.pas',
  ORM.Pais in 'ORM\ORM.Pais.pas',
  ORM.RHOcorrencia in 'ORM\ORM.RHOcorrencia.pas',
  ORM.TpCobranca in 'ORM\ORM.TpCobranca.pas',
  ORM.TpFrete in 'ORM\ORM.TpFrete.pas',
  ORM.Periodicidade in 'ORM\ORM.Periodicidade.pas',
  ORM.adntfornecedor in 'ORM\ORM.adntfornecedor.pas',
  ORM.Lp1a in 'ORM\ORM.Lp1a.pas',
  ORM.Condpagto in 'ORM\ORM.Condpagto.pas',
  ORM.AtivoPisCofins in 'ORM\ORM.AtivoPisCofins.pas',
  ORM.Negociacao in 'ORM\ORM.Negociacao.pas',
  orm.plconta in 'ORM\orm.plconta.pas',
  orm.cntcusto in 'ORM\orm.cntcusto.pas',
  orm.baixa in 'ORM\orm.baixa.pas',
  orm.plcontarateio in 'ORM\orm.plcontarateio.pas',
  orm.CntcustoRateio in 'ORM\orm.CntcustoRateio.pas',
  orm.itentrada in 'ORM\orm.itentrada.pas',
  orm.tpentrada in 'ORM\orm.tpentrada.pas',
  orm.tpmovto in 'ORM\orm.tpmovto.pas',
  orm.STApontamentoManual in 'ORM\orm.STApontamentoManual.pas',
  orm.TpApontamentoManual in 'ORM\orm.TpApontamentoManual.pas',
  orm.HAprovacaoAutpagto in 'ORM\orm.HAprovacaoAutpagto.pas',
  orm.Rmatividade in 'ORM\orm.Rmatividade.pas',
  orm.ClienteEntrega in 'ORM\orm.ClienteEntrega.pas',
  orm.StCliente in 'ORM\orm.StCliente.pas',
  orm.TpClienteMensalidade in 'ORM\orm.TpClienteMensalidade.pas',
  orm.TpCliente in 'ORM\orm.TpCliente.pas',
  orm.ItClienteCampanha in 'ORM\orm.ItClienteCampanha.pas',
  orm.ItClienteEmail in 'ORM\orm.ItClienteEmail.pas',
  orm.ItContCliente in 'ORM\orm.ItContCliente.pas',
  orm.ItCobranca in 'ORM\orm.ItCobranca.pas',
  orm.Parcela in 'ORM\orm.Parcela.pas',
  orm.Itcondpagto in 'ORM\orm.Itcondpagto.pas',
  orm.Stcondpagto in 'ORM\orm.Stcondpagto.pas',
  orm.SetBoleto in 'ORM\orm.SetBoleto.pas',
  orm.TpConta in 'ORM\orm.TpConta.pas',
  orm.ItContratoPaciente in 'ORM\orm.ItContratoPaciente.pas',
  orm.ItContratoParcela in 'ORM\orm.ItContratoParcela.pas',
  orm.ItContratoNegociacao in 'ORM\orm.ItContratoNegociacao.pas',
  orm.TpContrato in 'ORM\orm.TpContrato.pas',
  orm.ItContrato in 'ORM\orm.ItContrato.pas',
  Pessoal.Turno in 'Pessoal\Pessoal.Turno.pas' {frmTurno},
  Pessoal.PontoTrabalho in 'Pessoal\Pessoal.PontoTrabalho.pas' {frmpontotrabalho},
  Pessoal.RhOcorrencia in 'Pessoal\Pessoal.RhOcorrencia.pas' {frmRHOcorrencia},
  Pessoal.Treinamento in 'Pessoal\Pessoal.Treinamento.pas' {frmTreinamento},
  Pessoal.DespesaConvenio in 'Pessoal\Pessoal.DespesaConvenio.pas' {frmdespesaconvenio},
  Producao.Formulacao in 'Producao\Producao.Formulacao.pas' {frmFormulacao},
  Producao.CorridaQuimica in 'Producao\Producao.CorridaQuimica.pas' {frmcorridaquimica},
  Producao.Parada in 'Producao\Producao.Parada.pas' {frmparada},
  Producao.Ordproducao in 'Producao\Producao.Ordproducao.pas' {frmordproducao},
  Producao.Apontamento in 'Producao\Producao.Apontamento.pas' {frmapontamento},
  Producao.RequisicaoProducao in 'Producao\Producao.RequisicaoProducao.pas' {frmrequisicaoproducao},
  Producao.apontamentomanual in 'Producao\Producao.apontamentomanual.pas' {frmApontamentoManual},
  Recalcular.PisCofins in 'Recalculo\Recalcular.PisCofins.pas',
  Recalcular.Comissao in 'Recalculo\Recalcular.Comissao.pas',
  Recalculo.SaidaPedidoQtAtendida in 'Recalculo\Recalculo.SaidaPedidoQtAtendida.pas',
  Recalculo.Adntcliente.Saldo in 'Recalculo\Recalculo.Adntcliente.Saldo.pas',
  Recalculo.CustoMedio in 'Recalculo\Recalculo.CustoMedio.pas',
  Recalculo.SaldoConta in 'Recalculo\Recalculo.SaldoConta.pas',
  Recalculo.EstoqueTerceiro in 'Recalculo\Recalculo.EstoqueTerceiro.pas',
  Rotina.XLConst in 'Rotina\Rotina.XLConst.pas',
  Rotina.Tipo in 'Rotina\Rotina.Tipo.pas',
  Rotina.Protector in 'Rotina\Rotina.Protector.pas',
  Rotina.Numero in 'Rotina\Rotina.Numero.pas',
  Rotina.DataHora in 'Rotina\Rotina.DataHora.pas',
  Rotina.Replicacao in 'Rotina\Rotina.Replicacao.pas',
  Rotina.RegistroIb in 'Rotina\Rotina.RegistroIb.pas',
  Rotina.Rotinas in 'Rotina\Rotina.Rotinas.pas',
  Rotina.Registro in 'Rotina\Rotina.Registro.pas',
  Rotina.System in 'Rotina\Rotina.System.pas',
  Rotina.Interbase in 'Rotina\Rotina.Interbase.pas',
  Rotina.ValidaDocumento in 'Rotina\Rotina.ValidaDocumento.pas',
  Rotina.Strings in 'Rotina\Rotina.Strings.pas',
  Rotina.MontarSQL in 'Rotina\Rotina.MontarSQL.pas',
  Rotina.Arquivo in 'Rotina\Rotina.Arquivo.pas',
  Rotina.Retornasql in 'Rotina\Rotina.Retornasql.pas',
  Rotina.Consiste in 'Rotina\Rotina.Consiste.pas',
  Rotina.Sqlmontar in 'Rotina\Rotina.Sqlmontar.pas',
  Rotina.AdicionarListView in 'Rotina\Rotina.AdicionarListView.pas',
  Rotina.Consulta in 'Rotina\Rotina.Consulta.pas',
  Rotina.GerarProdutoMensalidade in 'Rotina\Rotina.GerarProdutoMensalidade.pas',
  TpResposta in 'Tipo\TpResposta.pas' {frmTpResposta},
  TpCriterioOrcamento in 'Tipo\TpCriterioOrcamento.pas' {frmtpcriterioorcamento},
  TpEntrada in 'Tipo\TpEntrada.pas' {frmtpentrada},
  TpProduto in 'Tipo\TpProduto.pas' {frmtpproduto},
  TpSaida in 'Tipo\TpSaida.pas' {frmtpsaida},
  TpAprovacao in 'Tipo\TpAprovacao.pas' {frmtpaprovacao},
  TpOrdserv in 'Tipo\TpOrdserv.pas' {frmtpordserv},
  TpAnotacao in 'Tipo\TpAnotacao.pas' {frmtpanotacao},
  TpLocacao in 'Tipo\TpLocacao.pas' {frmtplocacao},
  TpPedido in 'Tipo\TpPedido.pas' {frmtppedido},
  TpOrdcompra in 'Tipo\TpOrdcompra.pas' {frmtpordcompra},
  TpPedidomaterial in 'Tipo\TpPedidomaterial.pas' {frmtppedidomaterial},
  TpRim in 'Tipo\TpRim.pas' {frmtprim},
  TpOrcamento in 'Tipo\TpOrcamento.pas' {frmtporcamento},
  TpFaturamento in 'Tipo\TpFaturamento.pas' {frmtpfaturamento},
  TpEquipamento in 'Tipo\TpEquipamento.pas' {frmtpequipamento},
  TpContrato in 'Tipo\TpContrato.pas' {frmtpcontrato},
  TpOrdproducao in 'Tipo\TpOrdproducao.pas' {frmtpordproducao},
  TpEmbarque in 'Tipo\TpEmbarque.pas' {frmtpembarque},
  TpApontamentoManual in 'Tipo\TpApontamentoManual.pas' {frmtpapontamentomanual},
  TpCorrecao in 'Tipo\TpCorrecao.pas' {frmtpcorrecao},
  Usuario.Papel in 'Usuario\Usuario.Papel.pas' {frmPapel},
  Usuario.Aplicacao in 'Usuario\Usuario.Aplicacao.pas' {frmAplicacao},
  Usuario.Usuario in 'Usuario\Usuario.Usuario.pas' {frmUsuario},
  Usuario.Permissao in 'Usuario\Usuario.Permissao.pas' {frmPermissao},
  orm.FretePedagio in 'ORM\orm.FretePedagio.pas',
  orm.ctetpmedida in 'ORM\orm.ctetpmedida.pas',
  orm.CteTpvlprestacao in 'ORM\orm.CteTpvlprestacao.pas',
  orm.ItCartaCorrecaoCte in 'ORM\orm.ItCartaCorrecaoCte.pas',
  orm.CTEInutilizacao in 'ORM\orm.CTEInutilizacao.pas',
  orm.CTEVlPrestacao in 'ORM\orm.CTEVlPrestacao.pas',
  orm.CTEInformacaoSeguro in 'ORM\orm.CTEInformacaoSeguro.pas',
  orm.ItCTEDocumentoAnterior in 'ORM\orm.ItCTEDocumentoAnterior.pas',
  orm.CTEDocumentoAnterior in 'ORM\orm.CTEDocumentoAnterior.pas',
  orm.CartaCorrecaoCTE in 'ORM\orm.CartaCorrecaoCTE.pas',
  orm.CTETransportadora in 'ORM\orm.CTETransportadora.pas',
  orm.CTERemetenteNota in 'ORM\orm.CTERemetenteNota.pas',
  orm.CTEQTDCarga in 'ORM\orm.CTEQTDCarga.pas',
  orm.Veiculo in 'ORM\orm.Veiculo.pas',
  orm.ItRegCobranca in 'ORM\orm.ItRegCobranca.pas',
  orm.TpEmbarque in 'ORM\orm.TpEmbarque.pas',
  orm.rateiocntcusto in 'ORM\orm.rateiocntcusto.pas',
  orm.rateioplconta in 'ORM\orm.rateioplconta.pas',
  orm.strateioplconta in 'ORM\orm.strateioplconta.pas',
  Model.ORM.Interfaces in 'Model\ORM\Model.ORM.Interfaces.pas',
  orm.strateiocntcusto in 'ORM\orm.strateiocntcusto.pas',
  orm.itrateioplconta in 'ORM\orm.itrateioplconta.pas',
  orm.itrateiocntcusto in 'ORM\orm.itrateiocntcusto.pas',
  orm.ItMovto in 'ORM\orm.ItMovto.pas',
  orm.itembarque in 'ORM\orm.itembarque.pas',
  orm.TpEquipamentoPreco in 'ORM\orm.TpEquipamentoPreco.pas',
  orm.tpequipamento in 'ORM\orm.tpequipamento.pas',
  orm.TpTemporizador in 'ORM\orm.TpTemporizador.pas',
  orm.ItFatCliente in 'ORM\orm.ItFatCliente.pas',
  orm.ItFatPedido in 'ORM\orm.ItFatPedido.pas',
  orm.ItFatProduto in 'ORM\orm.ItFatProduto.pas',
  orm.ItFatSaida in 'ORM\orm.ItFatSaida.pas',
  orm.StFaturamento in 'ORM\orm.StFaturamento.pas',
  orm.TpFaturamento in 'ORM\orm.TpFaturamento.pas',
  orm.RegiaoAplicacao in 'ORM\orm.RegiaoAplicacao.pas',
  orm.ItFormulacao in 'ORM\orm.ItFormulacao.pas',
  orm.StFormulacao in 'ORM\orm.StFormulacao.pas',
  orm.ItFornecedorConta in 'ORM\orm.ItFornecedorConta.pas',
  orm.ItfornecedorEmail in 'ORM\orm.ItfornecedorEmail.pas',
  orm.clfornecedor in 'ORM\orm.clfornecedor.pas',
  orm.Stfornecedor in 'ORM\orm.Stfornecedor.pas',
  orm.ItContFornecedor in 'ORM\orm.ItContFornecedor.pas',
  orm.ItImportacao in 'ORM\orm.ItImportacao.pas',
  orm.StLocacao in 'ORM\orm.StLocacao.pas',
  orm.LocacaoPeriodo in 'ORM\orm.LocacaoPeriodo.pas',
  orm.HStLocacao in 'ORM\orm.HStLocacao.pas',
  orm.LocacaoDevolucao in 'ORM\orm.LocacaoDevolucao.pas',
  orm.TpLocacao in 'ORM\orm.TpLocacao.pas',
  orm.Hstordproducao in 'ORM\orm.Hstordproducao.pas',
  orm.TpOrdproducao in 'ORM\orm.TpOrdproducao.pas',
  orm.ItOrdProducaoRecurso in 'ORM\orm.ItOrdProducaoRecurso.pas',
  orm.hcontasaldo in 'ORM\orm.hcontasaldo.pas',
  orm.itfuncionariodependente in 'ORM\orm.itfuncionariodependente.pas',
  orm.Lp1aAtivoPisCofins in 'ORM\orm.Lp1aAtivoPisCofins.pas',
  orm.Lp1aCiapi in 'ORM\orm.Lp1aCiapi.pas',
  orm.ItRegApuracao in 'ORM\orm.ItRegApuracao.pas',
  orm.ItApuracao in 'ORM\orm.ItApuracao.pas',
  orm.ItApuf in 'ORM\orm.ItApuf.pas',
  orm.ItUfp1a in 'ORM\orm.ItUfp1a.pas',
  orm.ItLp1a in 'ORM\orm.ItLp1a.pas',
  orm.TpMDFE in 'ORM\orm.TpMDFE.pas',
  orm.MDFEveiculo in 'ORM\orm.MDFEveiculo.pas',
  orm.MDFETransportadora in 'ORM\orm.MDFETransportadora.pas',
  orm.MDFEPedagio in 'ORM\orm.MDFEPedagio.pas',
  orm.MDFECarregamento in 'ORM\orm.MDFECarregamento.pas',
  orm.MDFELacre in 'ORM\orm.MDFELacre.pas',
  orm.MDFENFE in 'ORM\orm.MDFENFE.pas',
  orm.MDFECTE in 'ORM\orm.MDFECTE.pas',
  orm.MDFEDescarregamento in 'ORM\orm.MDFEDescarregamento.pas',
  orm.MDFEMunicipioPercurso in 'ORM\orm.MDFEMunicipioPercurso.pas',
  orm.MDFEUFPercurso in 'ORM\orm.MDFEUFPercurso.pas',
  orm.TpModulo in 'ORM\orm.TpModulo.pas',
  orm.Movimentacao in 'ORM\orm.Movimentacao.pas',
  orm.NegociacaoSaida in 'ORM\orm.NegociacaoSaida.pas',
  orm.NegociacaoEntrada in 'ORM\orm.NegociacaoEntrada.pas',
  orm.StNegociacao in 'ORM\orm.StNegociacao.pas',
  orm.StOrcamento in 'ORM\orm.StOrcamento.pas',
  orm.itorcamentocusto in 'ORM\orm.itorcamentocusto.pas',
  orm.itorcamentomaterial in 'ORM\orm.itorcamentomaterial.pas',
  orm.ItorcamentoRecurso in 'ORM\orm.ItorcamentoRecurso.pas',
  orm.ITorcamento in 'ORM\orm.ITorcamento.pas',
  orm.TPOrcamento in 'ORM\orm.TPOrcamento.pas',
  orm.OrdcompraAprovacao in 'ORM\orm.OrdcompraAprovacao.pas',
  orm.OrdCompraAutpagto in 'ORM\orm.OrdCompraAutpagto.pas',
  orm.ITordcompra in 'ORM\orm.ITordcompra.pas',
  orm.TpOrdCompra in 'ORM\orm.TpOrdCompra.pas',
  orm.StOrdCompra in 'ORM\orm.StOrdCompra.pas',
  orm.ItOrdProducaoMaterial in 'ORM\orm.ItOrdProducaoMaterial.pas',
  orm.ItOrdproducaoCusto in 'ORM\orm.ItOrdproducaoCusto.pas',
  orm.ItOrdproducao in 'ORM\orm.ItOrdproducao.pas',
  orm.HCustoMedio in 'ORM\orm.HCustoMedio.pas',
  orm.ItGradeValor in 'ORM\orm.ItGradeValor.pas',
  orm.TpGradeValor in 'ORM\orm.TpGradeValor.pas',
  orm.Unidade in 'ORM\orm.Unidade.pas',
  orm.Norma in 'ORM\orm.Norma.pas',
  orm.Forma in 'ORM\orm.Forma.pas',
  orm.Material in 'ORM\orm.Material.pas',
  orm.Grupo in 'ORM\orm.Grupo.pas',
  orm.Modbcsticms in 'ORM\orm.Modbcsticms.pas',
  orm.Modbcicms in 'ORM\orm.Modbcicms.pas',
  orm.ProdutoFornecedor in 'ORM\orm.ProdutoFornecedor.pas',
  orm.itprodutocusto in 'ORM\orm.itprodutocusto.pas',
  orm.ProdutoFormulacao in 'ORM\orm.ProdutoFormulacao.pas',
  orm.ItProdutoRecurso in 'ORM\orm.ItProdutoRecurso.pas',
  orm.ItProdutoMaterial in 'ORM\orm.ItProdutoMaterial.pas',
  orm.TPProduto in 'ORM\orm.TPProduto.pas',
  orm.Prioridade in 'ORM\orm.Prioridade.pas',
  orm.ItOrdserv in 'ORM\orm.ItOrdserv.pas',
  orm.ItAcessorio in 'ORM\orm.ItAcessorio.pas',
  orm.ItDefApr in 'ORM\orm.ItDefApr.pas',
  orm.TPOrdserv in 'ORM\orm.TPOrdserv.pas',
  orm.ParcelamentoEntrada in 'ORM\orm.ParcelamentoEntrada.pas',
  orm.ParcelamentoSaida in 'ORM\orm.ParcelamentoSaida.pas',
  orm.StParcelamento in 'ORM\orm.StParcelamento.pas',
  orm.PedidoDuplicata in 'ORM\orm.PedidoDuplicata.pas',
  orm.ItPedidoEstrutura in 'ORM\orm.ItPedidoEstrutura.pas',
  orm.ITPedido in 'ORM\orm.ITPedido.pas',
  orm.stpedido in 'ORM\orm.stpedido.pas',
  orm.TPPedido in 'ORM\orm.TPPedido.pas',
  orm.HStPedidoMaterial in 'ORM\orm.HStPedidoMaterial.pas',
  orm.StPedidoMaterial in 'ORM\orm.StPedidoMaterial.pas',
  orm.TpPedidoMaterial in 'ORM\orm.TpPedidoMaterial.pas',
  orm.PedidoMaterialFornecedor in 'ORM\orm.PedidoMaterialFornecedor.pas',
  orm.ItPedidoMaterialFornecedor in 'ORM\orm.ItPedidoMaterialFornecedor.pas',
  orm.ItPedidoMaterial in 'ORM\orm.ItPedidoMaterial.pas',
  orm.TpAbono in 'ORM\orm.TpAbono.pas',
  orm.ItTurno in 'ORM\orm.ItTurno.pas',
  orm.Turno in 'ORM\orm.Turno.pas',
  orm.CartaoPonto in 'ORM\orm.CartaoPonto.pas',
  orm.FolhaPonto in 'ORM\orm.FolhaPonto.pas',
  orm.ItRegraStMVA in 'ORM\orm.ItRegraStMVA.pas',
  orm.ItRegraST in 'ORM\orm.ItRegraST.pas',
  orm.StRepresentante in 'ORM\orm.StRepresentante.pas',
  orm.ItRequisicaoProducao in 'ORM\orm.ItRequisicaoProducao.pas',
  orm.STRequisicaoProducao in 'ORM\orm.STRequisicaoProducao.pas',
  orm.TPRequisicaoProducao in 'ORM\orm.TPRequisicaoProducao.pas',
  orm.ItRim in 'ORM\orm.ItRim.pas',
  orm.TpRim in 'ORM\orm.TpRim.pas',
  orm.ItRotaValor in 'ORM\orm.ItRotaValor.pas',
  orm.ItRota in 'ORM\orm.ItRota.pas',
  orm.TpRota in 'ORM\orm.TpRota.pas',
  orm.TpAprovacaoUsuarios in 'ORM\orm.TpAprovacaoUsuarios.pas',
  orm.TpAprovacaoGrupos in 'ORM\orm.TpAprovacaoGrupos.pas',
  orm.ItTpCorrecao in 'ORM\orm.ItTpCorrecao.pas',
  orm.ITTransportadoraEmail in 'ORM\orm.ITTransportadoraEmail.pas',
  orm.StTransportadora in 'ORM\orm.StTransportadora.pas',
  orm.STICMS in 'ORM\orm.STICMS.pas',
  orm.UFLimite in 'ORM\orm.UFLimite.pas',
  orm.UFOrigemDestino in 'ORM\orm.UFOrigemDestino.pas',
  orm.hstorcamento in 'ORM\orm.hstorcamento.pas',
  acbr.MDFEGerar in 'ACBR\acbr.MDFEGerar.pas',
  orm.mdfeinfunidtranspcte in 'ORM\orm.mdfeinfunidtranspcte.pas',
  orm.mdfeinfunidcargacte in 'ORM\orm.mdfeinfunidcargacte.pas',
  orm.mdfelacunidtranspcte in 'ORM\orm.mdfelacunidtranspcte.pas',
  orm.mdfelacunidcargacte in 'ORM\orm.mdfelacunidcargacte.pas',
  orm.mdfeautxml in 'ORM\orm.mdfeautxml.pas',
  model.mdfe in 'Model\model.mdfe.pas' {dmMdfe: TDataModule};

{$R *.res}

begin
  if (ParamStr(1) <> 'n') and // parametro para n perguntar quando faz atualizacao do banco de dados
     (not ContinuarAplicacaoMaisdeUmaInstancia) then // se já houver uma instância da aplicação funcionando
  begin
    exit;
  end;
  Windows.DeleteFile(_atualizacao+'.'+_exe);
  qrotinas.SetDecimalSeparator;
  dtmMain            := TDtmMain.Create(application);
  vgChaveAplicacao   := _QUIPOS;
  aplicacao          := TAplicacao.create(dtmmain.sqlc, dtmmain.confire, vgChaveAplicacao);
  ACBR.acbr.ACBR     := TACBR.create;
  qp_nmcomputador    := nomedocomputador;
  try
    if not efetuarLogin then
    begin
      exit;
    end;
    Application.Initialize;
    Application.Title         := 'Quipos';
    Application.HintHidePause := 20000;
    Application.CreateForm(Tfrmmain, frmmain);
    acbr.acbr.acbr.lerconfiguracao;
    application.run;
  finally
    FreeAndNil(dtmMain);
    FreeAndNil(empresa);
    FreeAndNil(aplicacao);
    freeandnil(acbr.acbr.acbr);
    FreeAndNil(orm.usuario.usuario);
  end;
end.
