unit orm.TPPedido;

interface

uses Data.DB,
  Classe.DAO;

type
  TTPPedido = class(TRegistroQuipos)
  private
    fboitemdsproduto : String;
    fboitemexibirtag2 : String;
    fboitemconferencia : String;
    fboitemtp : String;
    fboitemprecoprazo : String;
    fboitemdtemissao : String;
    fboitemacrescimo : String;
    fbonuestrutural : String;
    fboitemvlunitariomaiorvenda : String;
    fboitemvlminimo : String;
    fboitemdescontomaximo : String;
    fboitemchecknuclfiscal : String;
    fboitemvlunitarionegativo : String;
    fboitemproducao : String;
    fboitemrevisao : String;
    fboitemvlunitariozerado : String;
    fboitemobservacao : String;
    fboitemobservacaoinfadicional : String;
    fboitemdesconto : String;
    fboitemfornecedor : String;
    fboitemprofissional : String;
    fboitemembarque : String;
    fboitemfrete : String;
    fboitemtprevisaocomercial : String;
    fboitemformula : String;
    Fboitemobservacaointerna: String;
    fcdprofissional : Integer;
    fcdtpordproducao : integer;
    fcdtpfrete : String;
    fnmcditpedido : string;
    femailcopia : string;
    fdsassunto : string;
    fcdtppedido : integer;
    fcdtpsaida : integer;
    fnmtppedido : string;
    fdstitulo : string;
    fprdescontomaximo : Double;
    fboinfadicionalordcompra : String;
    fboacrescimo : String;
    fboinfadicionalformula : String;
    fboobservacaocopiarsaida : String;
    fbofornecedor : String;
    fboordproducaogerarautomatico : String;
    fbodescontoassinatura : String;
    fboorcamento : String;
    fboarquivo : String;
    fboduplicata : String;
    fboredespacho : String;
    fbocomissao : String;
    fborepresentante : String;
    fboestoque : String;
    fboprfretecidade : String;
    fboavisotarefa : String;
    fboordproducao : String;
    fboordproducaoqtitem : String;
    fboalterarvaloritem : String;
    fboreportmodotexto : String;
    fboreportmodotexto2 : String;
    fboreportorcamento : String;
    fboreportvenda : String;
    fboreportvendasimples : String;
    fboclienteentrega : String;
    fboicmssubtrib : String;
    fbomadeira : String;
    fborepresentanteusuario : String;
    fbofuncionariousuario : String;
    fbofrete : String;
    fbotransportadora : String;
    fbotransportadoraobrigatorio : String;
    fbofuncionario : String;
    fbonudias : String;
    fboicms : String;
    fboipi : String;
    fbodesconto : String;
    fbotpcobranca : String;
    fbodescontocomissao : String;
    fbotpgrade : String;
    fbodtprventregaitem : String;
    fbocotacao : String;
    fbocotacaoobrigatorio : String;
    fbonuitem : String;
    fbocertificado : String;
    fbocotacaoitem : String;
    fbocotacaoitemobrigatorio : String;
    fbodsdesenho : String;
    fboclienteatraso : String;
    fboitcontcliente : String;
    fboreportordemproducao : String;
    fbodsobservacaocliente : String;
    fboclienteconsistir : String;
    fboprofissional : String;
    fboprodutoembalagem : String;
    fnudiasentrega : integer;
    Fbodsreferenciaobrigatorio: String;
    fbopaciente: String;
    fbopacientealterarprofissao: String;
    fbopacientedtdemissao: String;
    fcdstpaciente : integer;
    fcdfaturista: integer;
    fboiss: String;
    Fbotpfreteobrigatorio: String;
    fboitemvlunitariotpcobranca: String;
    Fbofretentotal: String;
    Fborepresentanteobrigatorio: string;
    Fbocondpagtoobrigatorio: string;
    Fbotpcobrancaobrigatorio: string;
    fbodtentregaobrigatorio: string;
    fbodtentregavazio: string;
    fbodtfechamentodigitar: string;
    fbopedidobalcao: string;
    fcdcliente: Largeint;
  public
    [keyfield]
    property cdtppedido : integer read fcdtppedido write fcdtppedido;
    [fk]
    property cdfaturista : integer read fcdfaturista write fcdfaturista;
    [fk]
    property cdcliente: Largeint read fcdcliente write fcdcliente;
    property bopaciente: String read fbopaciente write fbopaciente;
    property bopacientealterarprofissao: String read fbopacientealterarprofissao write fbopacientealterarprofissao;
    property bopacientedtdemissao: String read fbopacientedtdemissao write fbopacientedtdemissao;
    [fk]
    property cdstpaciente : integer read fcdstpaciente write fcdstpaciente;
    property boitemdsproduto : String read fboitemdsproduto write fboitemdsproduto;
    property boitemexibirtag2 : String read fboitemexibirtag2 write fboitemexibirtag2;
    property boitemconferencia : String read fboitemconferencia write fboitemconferencia;
    property boitemtp : String read fboitemtp write fboitemtp;
    property boitemprecoprazo : String read fboitemprecoprazo write fboitemprecoprazo;
    property boitemdtemissao : String read fboitemdtemissao write fboitemdtemissao;
    property boitemacrescimo : String read fboitemacrescimo write fboitemacrescimo;
    property bonuestrutural : String read fbonuestrutural write fbonuestrutural;
    property boitemvlunitariomaiorvenda : String read fboitemvlunitariomaiorvenda write fboitemvlunitariomaiorvenda;
    property boitemvlminimo : String read fboitemvlminimo write fboitemvlminimo;
    property boitemdescontomaximo : String read fboitemdescontomaximo write fboitemdescontomaximo;
    property boitemchecknuclfiscal : String read fboitemchecknuclfiscal write fboitemchecknuclfiscal;
    property boitemvlunitarionegativo : String read fboitemvlunitarionegativo write fboitemvlunitarionegativo;
    property boitemproducao : String read fboitemproducao write fboitemproducao;
    property boitemrevisao : String read fboitemrevisao write fboitemrevisao;
    property boitemvlunitariozerado : String read fboitemvlunitariozerado write fboitemvlunitariozerado;
    property boitemobservacao : String read fboitemobservacao write fboitemobservacao;
    property boitemobservacaoinfadicional : String read fboitemobservacaoinfadicional write fboitemobservacaoinfadicional;
    property boitemdesconto : String read fboitemdesconto write fboitemdesconto;
    property boitemfornecedor : String read fboitemfornecedor write fboitemfornecedor;
    property boitemprofissional : String read fboitemprofissional write fboitemprofissional;
    property boitemembarque : String read fboitemembarque write fboitemembarque;
    property boitemfrete : String read fboitemfrete write fboitemfrete;
    property boitemtprevisaocomercial : String read fboitemtprevisaocomercial write fboitemtprevisaocomercial;
    property boitemformula : String read fboitemformula write fboitemformula;
    property boitemobservacaointerna : String read Fboitemobservacaointerna write Fboitemobservacaointerna;
    [fk]
    property cdprofissional : Integer read fcdprofissional write fcdprofissional;
    [fk]
    property cdtpordproducao : integer read fcdtpordproducao write fcdtpordproducao;
    [fk]
    property cdtpfrete : String read fcdtpfrete write fcdtpfrete;
    property nmcditpedido : string read fnmcditpedido write fnmcditpedido;
    property emailcopia : string read femailcopia write femailcopia;
    property dsassunto : string read fdsassunto write fdsassunto;
    property cdtpsaida : integer read fcdtpsaida write fcdtpsaida;
    property nmtppedido : string read fnmtppedido write fnmtppedido;
    property dstitulo : string read fdstitulo write fdstitulo;
    property prdescontomaximo : Double read fprdescontomaximo write fprdescontomaximo;
    property boinfadicionalordcompra : String read fboinfadicionalordcompra write fboinfadicionalordcompra;
    property boacrescimo : String read fboacrescimo write fboacrescimo;
    property boinfadicionalformula : String read fboinfadicionalformula write fboinfadicionalformula;
    property boobservacaocopiarsaida : String read fboobservacaocopiarsaida write fboobservacaocopiarsaida;
    property bofornecedor : String read fbofornecedor write fbofornecedor;
    property boordproducaogerarautomatico : String read fboordproducaogerarautomatico write fboordproducaogerarautomatico;
    property bodescontoassinatura : String read fbodescontoassinatura write fbodescontoassinatura;
    property boorcamento : String read fboorcamento write fboorcamento;
    property boarquivo : String read fboarquivo write fboarquivo;
    property boduplicata : String read fboduplicata write fboduplicata;
    property boredespacho : String read fboredespacho write fboredespacho;
    property bocomissao : String read fbocomissao write fbocomissao;
    property borepresentante : String read fborepresentante write fborepresentante;
    property boestoque : String read fboestoque write fboestoque;
    property boprfretecidade : String read fboprfretecidade write fboprfretecidade;
    property boavisotarefa : String read fboavisotarefa write fboavisotarefa;
    property boordproducao : String read fboordproducao write fboordproducao;
    property boordproducaoqtitem : String read fboordproducaoqtitem write fboordproducaoqtitem;
    property boalterarvaloritem : String read fboalterarvaloritem write fboalterarvaloritem;
    property boreportmodotexto : String read fboreportmodotexto write fboreportmodotexto;
    property boreportmodotexto2 : String read fboreportmodotexto2 write fboreportmodotexto2;
    property boreportorcamento : String read fboreportorcamento write fboreportorcamento;
    property boreportvenda : String read fboreportvenda write fboreportvenda;
    property boreportvendasimples : String read fboreportvendasimples write fboreportvendasimples;
    property boclienteentrega : String read fboclienteentrega write fboclienteentrega;
    property boicmssubtrib : String read fboicmssubtrib write fboicmssubtrib;
    property bomadeira : String read fbomadeira write fbomadeira;
    property borepresentanteusuario : String read fborepresentanteusuario write fborepresentanteusuario;
    property bofuncionariousuario : String read fbofuncionariousuario write fbofuncionariousuario;
    property bofrete : String read fbofrete write fbofrete;
    property botransportadora : String read fbotransportadora write fbotransportadora;
    property botransportadoraobrigatorio : String read fbotransportadoraobrigatorio write fbotransportadoraobrigatorio;
    property bofuncionario : String read fbofuncionario write fbofuncionario;
    property bonudias : String read fbonudias write fbonudias;
    property boicms : String read fboicms write fboicms;
    property boipi : String read fboipi write fboipi;
    property bodesconto : String read fbodesconto write fbodesconto;
    property botpcobranca : String read fbotpcobranca write fbotpcobranca;
    property bodescontocomissao : String read fbodescontocomissao write fbodescontocomissao;
    property botpgrade : String read fbotpgrade write fbotpgrade;
    property bodtprventregaitem : String read fbodtprventregaitem write fbodtprventregaitem;
    property bocotacao : String read fbocotacao write fbocotacao;
    property bocotacaoobrigatorio : String read fbocotacaoobrigatorio write fbocotacaoobrigatorio;
    property bonuitem : String read fbonuitem write fbonuitem;
    property bocertificado : String read fbocertificado write fbocertificado;
    property bocotacaoitem : String read fbocotacaoitem write fbocotacaoitem;
    property bocotacaoitemobrigatorio : String read fbocotacaoitemobrigatorio write fbocotacaoitemobrigatorio;
    property bodsdesenho : String read fbodsdesenho write fbodsdesenho;
    property boclienteatraso : String read fboclienteatraso write fboclienteatraso;
    property boitcontcliente : String read fboitcontcliente write fboitcontcliente;
    property boreportordemproducao : String read fboreportordemproducao write fboreportordemproducao;
    property bodsobservacaocliente : String read fbodsobservacaocliente write fbodsobservacaocliente;
    property boclienteconsistir : String read fboclienteconsistir write fboclienteconsistir;
    property boprofissional : String read fboprofissional write fboprofissional;
    property boprodutoembalagem : String read fboprodutoembalagem write fboprodutoembalagem;
    property nudiasentrega : integer read fnudiasentrega write fnudiasentrega;
    property bodsreferenciaobrigatorio : String read Fbodsreferenciaobrigatorio write Fbodsreferenciaobrigatorio;
    property boiss : String read fboiss write fboiss;
    property botpfreteobrigatorio : String read Fbotpfreteobrigatorio write Fbotpfreteobrigatorio;
    property boitemvlunitariotpcobranca : String read fboitemvlunitariotpcobranca write fboitemvlunitariotpcobranca;
    property bofretentotal : String read Fbofretentotal write Fbofretentotal;
    property borepresentanteobrigatorio : string read Fborepresentanteobrigatorio write Fborepresentanteobrigatorio;
    property bocondpagtoobrigatorio : string read Fbocondpagtoobrigatorio write Fbocondpagtoobrigatorio;
    property botpcobrancaobrigatorio : string read Fbotpcobrancaobrigatorio write Fbotpcobrancaobrigatorio;
    property bodtentregaobrigatorio : string read fbodtentregaobrigatorio write fbodtentregaobrigatorio;
    property bodtentregavazio : string read fbodtentregavazio write fbodtentregavazio;
    property bodtfechamentodigitar: string read fbodtfechamentodigitar write fbodtfechamentodigitar;
    property bopedidobalcao: string read fbopedidobalcao write fbopedidobalcao;
  end;

implementation

end.
