unit orm.TPOrcamento;

interface

uses Classe.DAO;

type
  TTPOrcamento = class(TRegistroQuipos)
  private
    fbomarkupdespesacomercial : String;
    fbomarkupfrete : String;
    fbomarkupembalagem : String;
    fbomarkupseguro : String;
    fbomarkupdespesaadministrativa : String;
    fprmarkupembalagem : Double;
    fprmarkupfrete : Double;
    fprmarkupseguro : Double;
    fprmarkupdespesaadministrativa : Double;
    fprmarkupdespesacomercial : Double;
    fprmarkuplucro : Double;
    fprmarkupircs : double;
    fboitemtp : String;
    fboitemanalisecritica : String;
    fboitemacrescimo : String;
    fboitemdsproduto : String;
    fboitemdesenhoanterior : String;
    fboitemdescricao : String;
    fboitemvlminimo : String;
    fboitemdescontomaximo : String;
    fboitemdesconto : String;
    fboitemmaterialpis : String;
    fboitemmaterialcofins : String;
    fboitemnuclfiscal : String;
    fboitemdtaprovacao : String;
    fboitemnuprazoentrega : String;
    fboitemtpicms : String;
    fboitemtpipi : String;
    fboitemformula : String;
    fboitemmaterial : String;
    fboitemmaterialformula : String;
    fboitemcusto : String;
    fboitemdesenhoposicao : String;
    fboitemdesenhorevisao : String;
    fboitemrecurso : String;
    fboitemrecursoalteravalor : String;
    fboitemrecursooperacao : String;
    fboitemrecursopreparacao : String;
    fboitemcondpagto : String;
    fboitemalterarvalor : String;
    fboitemperiodicidade: String;
    fboitemcdperiodicidade: String;
    fboacrescimo : String;
    fboprodutoembalagem: String;
    fbocopiardiasemana : String;
    fboproduto : String;
    fbogerarrequisicaoproducao : String;
    fbocontrato: String;
    fboreportanalitico: String;
    fboreportorcamento: String;
    fboobservacao: String;
    fboobservacaocopiar: String;
    fboobservacaointerna: String;
    fboclienteentrega: String;
    fborepresentante: String;
    fboclientereferencia: String;
    fbodsobservacaocliente: String;
    fboexibirnmcliente: String;
    fboexibirfrete: String;
    fboicmssubtrib: String;
    fbodsobservacaoitem: String;
    fbomadeira: String;
    fbofrete: String;
    fbotransportadora: String;
    fbofuncionario: String;
    fbofuncionarioorcamentista: String;
    fbocertificado: String;
    fboinftecnica: String;
    fbocaldeiraria: String;
    fbofuncionariousuario: String;
    fbonudias: String;
    fbonusequencia: String;
    fboicms: String;
    fboipi: String;
    fbodesconto: String;
    fbotpcobranca: String;
    fbotpgrade: String;
    fbodtprventregaitem: String;
    fbocalculo: String;
    fbocotacao: String;
    fbonuitem: String;
    fboitcontcliente: String;
    fboanalisecritica: String;
    fbocomercial: String;
    fbocotacaoitem: String;
    fbodsdesenho: String;
    fboarquivo: String;
    femailcopia : string;
    fcdtpipi : integer;
    fdsobservacao : string;
    fcdtpfrete : String;
    ftpdata : string;
    fdstitulodimensional : string;
    faliss : Double;
    falicms : Double;
    falpisservico : Double;
    falpis : Double;
    falipi : Double;
    falcofinsservico : Double;
    falcofins : Double;
    falirpj : Double;
    falirpjservico : Double;
    falcsll : Double;
    falcsllservico : Double;
    falsimples : Double;
    falsimplesservico : Double;
    fnudiasentrega : Integer;
    fnudiasvalidade : Integer;
    Fboprmulta: String;
    Fboprmoradiaria: String;
    Fbonudiasrescisao: String;
    Fbodstag2: String;
    Fbonudiasmedicao: String;
    Fbodstag: String;
    Fbodstag3: String;
    Fbodstag4: String;
    Fnmdstag3: string;
    Fnmdstag: string;
    Fnmdstag2: string;
    Fnmdstag4: string;
    fcdtppedidomaterial: Integer;
    fboiss: String;
    fbojustificarmudancastatus: String;
    fboitemvlunitariotpcobranca: String;
    Fnmperiodicidade: string;
    Fdsnudias: string;
    Fdsreferencia: string;
    Fdsorcamentista: string;
    Fdsrepresentante: string;
    Fdsresponsavel: string;
    Fbodstag5: String;
    Fnmdstag5: string;
    Fcdtporcamento: integer;
    fnmtporcamento : string;
    Fbomarkupcpp: string;
    Fdsassuntoemail: string;
    Fboexibiralternativo: string;
    Fdstituloemail: string;
    Fboitemperfil: string;
    Fboitemetapa: string;
    Fbocriterioorcamento: string;
    Fbofuncionariovendedor: string;
  public
    [keyfield]
    property cdtporcamento : integer read Fcdtporcamento write Fcdtporcamento;
    property cdtpipi : integer read fcdtpipi write fcdtpipi;
    property cdtpfrete : string read fcdtpfrete write fcdtpfrete;
    property cdtppedidomaterial : Integer read fcdtppedidomaterial write fcdtppedidomaterial;
    property nmtporcamento : string read fnmtporcamento write fnmtporcamento;
    property boicms: String read fboicms write fboicms;
    property boipi: String read fboipi write fboipi;
    property bodesconto: String read fbodesconto write fbodesconto;
    property botpcobranca: String read fbotpcobranca write fbotpcobranca;
    property botpgrade: String read fbotpgrade write fbotpgrade;
    property bocotacao: String read fbocotacao write fbocotacao;
    property bodtprventregaitem: String read fbodtprventregaitem write fbodtprventregaitem;
    property bocalculo: String read fbocalculo write fbocalculo;
    property bofuncionariovendedor : string read Fbofuncionariovendedor write Fbofuncionariovendedor;
    property bofuncionarioorcamentista: String read fbofuncionarioorcamentista write fbofuncionarioorcamentista;
    property bonudias: String read fbonudias write fbonudias;
    property bofrete: String read fbofrete write fbofrete;
    property botransportadora: String read fbotransportadora write fbotransportadora;
    property boicmssubtrib: String read fboicmssubtrib write fboicmssubtrib;
    property bodsdesenho: String read fbodsdesenho write fbodsdesenho;
    property boexibiralternativo : string read Fboexibiralternativo write Fboexibiralternativo;
    property bocotacaoitem : String read fbocotacaoitem write fbocotacaoitem;
    property bonuitem: String read fbonuitem write fbonuitem;
    property bomadeira: String read fbomadeira write fbomadeira;
    property nudiasentrega : Integer read fnudiasentrega write fnudiasentrega;
    property boexibirnmcliente: String read fboexibirnmcliente write fboexibirnmcliente;
    property boexibirfrete: String read fboexibirfrete write fboexibirfrete;
    property bofuncionario: String read fbofuncionario write fbofuncionario;
    property bofuncionariousuario: String read fbofuncionariousuario write fbofuncionariousuario;
    property bodsobservacaoitem: String read fbodsobservacaoitem write fbodsobservacaoitem;
    property boitemalterarvalor : String read fboitemalterarvalor write fboitemalterarvalor;
    property bodsobservacaocliente: String read fbodsobservacaocliente write fbodsobservacaocliente;
    property boitemtpicms : String read fboitemtpicms write fboitemtpicms;
    property boitemtpipi : String read fboitemtpipi write fboitemtpipi;
    property boitemdesenhoposicao : String read fboitemdesenhoposicao write fboitemdesenhoposicao;
    property boitemdesenhorevisao : String read fboitemdesenhorevisao write fboitemdesenhorevisao;
    property boitemformula : String read fboitemformula write fboitemformula;
    property boitemmaterial : String read fboitemmaterial write fboitemmaterial;
    property boitemcusto : String read fboitemcusto write fboitemcusto;
    property boitemrecurso : String read fboitemrecurso write fboitemrecurso;
    property boclientereferencia: String read fboclientereferencia write fboclientereferencia;
    property boitemperfil : string read Fboitemperfil write Fboitemperfil;
    property borepresentante: String read fborepresentante write fborepresentante;
    property boclienteentrega: String read fboclienteentrega write fboclienteentrega;
    property boobservacao: String read fboobservacao write fboobservacao;
    property boobservacaointerna: String read fboobservacaointerna write fboobservacaointerna;
    property nudiasvalidade : Integer read fnudiasvalidade write fnudiasvalidade;
    property boitemnuprazoentrega : String read fboitemnuprazoentrega write fboitemnuprazoentrega;
    property boitemdtaprovacao : String read fboitemdtaprovacao write fboitemdtaprovacao;
    property boitemnuclfiscal : String read fboitemnuclfiscal write fboitemnuclfiscal;
    property boitemmaterialcofins : String read fboitemmaterialcofins write fboitemmaterialcofins;
    property boitemmaterialpis : String read fboitemmaterialpis write fboitemmaterialpis;
    property prmarkupfrete : Double read fprmarkupfrete write fprmarkupfrete;
    property prmarkupembalagem : Double read fprmarkupembalagem write fprmarkupembalagem;
    property prmarkupseguro : Double read fprmarkupseguro write fprmarkupseguro;
    property prmarkupdespesaadministrativa : Double read fprmarkupdespesaadministrativa write fprmarkupdespesaadministrativa;
    property prmarkupdespesacomercial : Double read fprmarkupdespesacomercial write fprmarkupdespesacomercial;
    property prmarkuplucro : Double read fprmarkuplucro write fprmarkuplucro;
    property prmarkupircs : double read fprmarkupircs write fprmarkupircs;
    property bomarkupfrete : String read fbomarkupfrete write fbomarkupfrete;
    property bomarkupembalagem : String read fbomarkupembalagem write fbomarkupembalagem;
    property bomarkupseguro : String read fbomarkupseguro write fbomarkupseguro;
    property bomarkupdespesaadministrativa : String read fbomarkupdespesaadministrativa write fbomarkupdespesaadministrativa;
    property bomarkupdespesacomercial : String read fbomarkupdespesacomercial write fbomarkupdespesacomercial;
    property bomarkupcpp : string read Fbomarkupcpp write Fbomarkupcpp;
    property aliss : Double read faliss write faliss;
    property alicms : Double read falicms write falicms;
    property alpisservico : Double read falpisservico write falpisservico;
    property alpis : Double read falpis write falpis;
    property alcofinsservico : Double read falcofinsservico write falcofinsservico;
    property alcofins : Double read falcofins write falcofins;
    property alirpj : Double read falirpj write falirpj;
    property alirpjservico : Double read falirpjservico write falirpjservico;
    property alcsll : Double read falcsll write falcsll;
    property alcsllservico : Double read falcsllservico write falcsllservico;
    property alsimples : Double read falsimples write falsimples;
    property alsimplesservico : Double read falsimplesservico write falsimplesservico;
    property alipi : Double read falipi write falipi;
    property boitemrecursoalteravalor : String read fboitemrecursoalteravalor write fboitemrecursoalteravalor;
    property boitemrecursopreparacao : String read fboitemrecursopreparacao write fboitemrecursopreparacao;
    property boitemrecursooperacao : String read fboitemrecursooperacao write fboitemrecursooperacao;
    property tpdata : string read ftpdata write ftpdata;
    property boitcontcliente: String read fboitcontcliente write fboitcontcliente;
    property boanalisecritica: String read fboanalisecritica write fboanalisecritica;
    property boitemdesconto : String read fboitemdesconto write fboitemdesconto;
    property bonusequencia: String read fbonusequencia write fbonusequencia;
    property dstituloemail : string read Fdstituloemail write Fdstituloemail;
    property dsassuntoemail : string read Fdsassuntoemail write Fdsassuntoemail;
    property emailcopia : string read femailcopia write femailcopia;
    property boitemdescricao : String read fboitemdescricao write fboitemdescricao;
    property bocomercial: String read fbocomercial write fbocomercial;
    property bocaldeiraria: String read fbocaldeiraria write fbocaldeiraria;
    property bocertificado: String read fbocertificado write fbocertificado;
    property boinftecnica: String read fboinftecnica write fboinftecnica;
    property boitemetapa : string read Fboitemetapa write Fboitemetapa;
    property boreportanalitico: String read fboreportanalitico write fboreportanalitico;
    property boreportorcamento: String read fboreportorcamento write fboreportorcamento;
    property boitemmaterialformula : String read fboitemmaterialformula write fboitemmaterialformula;
    property boitemcondpagto : String read fboitemcondpagto write fboitemcondpagto;
    property boobservacaocopiar: String read fboobservacaocopiar write fboobservacaocopiar;
    property dsobservacao : string read fdsobservacao write fdsobservacao;
    property boitemvlminimo : String read fboitemvlminimo write fboitemvlminimo;
    property boitemdescontomaximo : String read fboitemdescontomaximo write fboitemdescontomaximo;
    property bocontrato: String read fbocontrato write fbocontrato;
    property boitemdesenhoanterior : String read fboitemdesenhoanterior write fboitemdesenhoanterior;
    property boitemdsproduto : String read fboitemdsproduto write fboitemdsproduto;
    property boarquivo : String read fboarquivo write fboarquivo;
    property boprodutoembalagem: String read fboprodutoembalagem write fboprodutoembalagem;
    property bocopiardiasemana : String read fbocopiardiasemana write fbocopiardiasemana;
    property bogerarrequisicaoproducao : String read fbogerarrequisicaoproducao write fbogerarrequisicaoproducao;
    property boitemanalisecritica : String read fboitemanalisecritica write fboitemanalisecritica;
    property boacrescimo : String read fboacrescimo write fboacrescimo;
    property boitemacrescimo : String read fboitemacrescimo write fboitemacrescimo;
    property dstitulodimensional : string read fdstitulodimensional write fdstitulodimensional;
    property boproduto : String read fboproduto write fboproduto;
    property boitemtp : String read fboitemtp write fboitemtp;
    property boprmulta : String read Fboprmulta write fboprmulta;
    property boprmoradiaria : String read Fboprmoradiaria write fboprmoradiaria;
    property boitemperiodicidade : String read Fboitemperiodicidade write Fboitemperiodicidade;
    property bonudiasrescisao : String read Fbonudiasrescisao write Fbonudiasrescisao;
    property boitemcdperiodicidade : String read Fboitemcdperiodicidade write Fboitemcdperiodicidade;
    property bodstag : String read Fbodstag write Fbodstag;
    property bodstag2 : String read Fbodstag2 write Fbodstag2;
    property bodstag3 : String read Fbodstag3 write Fbodstag3;
    property bonudiasmedicao : String read Fbonudiasmedicao write Fbonudiasmedicao;
    property nmdstag : string read Fnmdstag write Fnmdstag;
    property nmdstag2 : string read Fnmdstag2 write Fnmdstag2;
    property nmdstag3 : string read Fnmdstag3 write Fnmdstag3;
    property bodstag4 : String read Fbodstag4 write Fbodstag4;
    property nmdstag4 : string read Fnmdstag4 write Fnmdstag4;
    property bocriterioorcamento : string read Fbocriterioorcamento write Fbocriterioorcamento;
    property boiss : String read fboiss write fboiss;
    property bojustificarmudancastatus : String read fbojustificarmudancastatus write fbojustificarmudancastatus;
    property boitemvlunitariotpcobranca : String read fboitemvlunitariotpcobranca write fboitemvlunitariotpcobranca;
    property nmperiodicidade : string read Fnmperiodicidade write Fnmperiodicidade;
    property dsnudias : string read Fdsnudias write Fdsnudias;
    property dsreferencia : string read Fdsreferencia write Fdsreferencia;
    property dsorcamentista : string read Fdsorcamentista write Fdsorcamentista;
    property dsrepresentante : string read Fdsrepresentante write Fdsrepresentante;
    property dsresponsavel : string read Fdsresponsavel write Fdsresponsavel;
    property nmdstag5 : string read Fnmdstag5 write Fnmdstag5;
    property bodstag5 : String read Fbodstag5 write Fbodstag5;
  end;

implementation

end.
