unit orm.TPOrdserv;

interface

uses Classe.DAO;

type
  TTPOrdserv = class(TRegistroQuipos)
  private
    fcdfuncaoatendente : integer;
    fcdfuncaotecnico : integer;
    fcdfuncaovendedor : integer;
    fbonuano : String;
    fbocor : String;
    fboprioridade : String;
    fbonukm : String;
    fbonubateria : String;
    fbodtaprovacao : String;
    fbohraprovacao : String;
    fbodtprevorcamento : String;
    fbohrprevorcamento : String;
    fboprevorcamentoobrigatorio : String;
    fbodtpreventrega: String;
    fbohrpreventrega : String;
    fbopreventregaobrigatorio : String;
    fbogarantia : String;
    fboprodutoexibircdalternativo : String;
    fboequipamentoguia : String;
    fbodigitarproduto : String;
    fboreportentregasemcomprovante : String;
    fbocomissaovendedor : String;
    fbocomissaotecnico : String;
    fbocomissaoorcado : String;
    fboassinaturadesconto : String;
    fbocomissaoorcadoproduto : String;
    fbocomissaoorcadoservico : String;
    fboetapa : String;
    fbocomissaoatendente : String;
    fborevisao : String;
    fbocomissaoatendenteproduto : String;
    fbocomissaotecnicoproduto : String;
    fbocomissaovendedorproduto : String;
    fbocomissaoatendenteservico : String;
    fboidentificadorcomissaoproduto : String;
    fbocomissaotecnicoservico : String;
    fbocomissaovendedorservico : String;
    fboreportorcamento : String;
    fnugerarcodigo : integer;
    fboequipamentolocal : String;
    fboqtdequipamentoobrigatorio : String;
    fbovendedorobrigatorio : String;
    fboatendenteobrigatorio : String;
    fbotecnicoobrigatorio : String;
    fboqtdequipamento : String;
    fbogradeprodutolocalizacao: String;
    fboprodutoobrigatorio : String;
    fboprodutoinsercaoobrigatorio : String;
    fbonupatrimonio : String;
    fboentrada : String;
    fbosaida : String;
    fbodevolucaosemconserto : String;
    fborepresentante : String;
    fbocliente : String;
    fboalterarvalor : String;
    fbotpgrade : String;
    fboservicoexterno : String;
    fboproduto : String;
    fboprodutoinsercao : String;
    fboacessorio : String;
    fbodefapr : String;
    fbodefenc : String;
    fboobservacao : String;
    fbosolucao : String;
    fboobservacaoanterior : String;
    fboobservacaotpordserv : String;
    fboobsinterna : String;
    fbosolinterna : String;
    fboosanterior : String;
    fboservico : String;
    fbopeca : String;
    fbofoto : String;
    fbodesenho : String;
    fbogeral : String;
    fbopintura : String;
    fboteste : String;
    fbodefeito : String;
    fboavaliacaotecnica : String;
    fboequipamento : String;
    fboequipamentoobrigatorio: String;
    fboatendente : String;
    fbotecnico : String;
    fbovendedor : String;
    fbonukmobrigatorio : String;
    fboreportabertura : String;
    fboreportentrega : String;
    fboreportacompanhamento: String;
    fboreportorcamentocontrato : String;
    fboreportorcamentoavulso : String;
    fbobaixaestoque : String;
    fbodtentradadigitar : String;
    fbohrentradadigitar : String;
    fbodtsaidadigitar : String;
    fbotpvoltagem : String;
    fbotpvoltagemobrigatorio : String;
    Fcdstordserventrega: integer;
    Fboreportaberturasalvar: String;
    Fbolocalservico: String;
    Fboselobalanca: String;
    Fbolacrebalanca: String;
    Fboreportordserv: string;
    Fboacessoriolista: string;
    Fboreportordservdtaprovacao: string;
    Fdslayoutequipamento: string;
    Fdsobservacao: string;
    Fbopreencheratendente: string;
    Fqtitem: integer;
    Fcdtpordserv: integer;
    Fdsobsimpressao: string;
    Fcdetapa: integer;
    Fcdstitordserventrada: integer;
    Fboativar: string;
    Fboexterno: string;
    Fcdstitordservbaixa: integer;
    Fcdtpmovtoentrada: integer;
    Fnmtpordserv: string;
    Fcdtpmovtobaixa: integer;
    fbonuserieobrigatorio: string;
    fbonupatrimonioobrigatorio: string;
  public
    [keyfield]
    property cdtpordserv : integer read Fcdtpordserv write Fcdtpordserv;
    [fk]
    property cdetapa : integer read Fcdetapa write Fcdetapa;
    [fk]
    property cdtpmovtobaixa : integer read Fcdtpmovtobaixa write Fcdtpmovtobaixa;
    [fk]
    property cdtpmovtoentrada : integer read Fcdtpmovtoentrada write Fcdtpmovtoentrada;
    [fk]
    property cdstitordservbaixa : integer read Fcdstitordservbaixa write Fcdstitordservbaixa;
    [fk]
    property cdstitordserventrada : integer read Fcdstitordserventrada write Fcdstitordserventrada;
    property nmtpordserv : string read Fnmtpordserv write Fnmtpordserv;
    property dsobservacao : string read Fdsobservacao write Fdsobservacao;
    property dsobsimpressao : string read Fdsobsimpressao write Fdsobsimpressao;
    property boreportordserv : string read Fboreportordserv write Fboreportordserv;
    property boacessoriolista : string read Fboacessoriolista write Fboacessoriolista;
    property qtitem : integer read Fqtitem write Fqtitem;
    property boreportordservdtaprovacao : string read Fboreportordservdtaprovacao write Fboreportordservdtaprovacao;
    property dslayoutequipamento : string read Fdslayoutequipamento write Fdslayoutequipamento;
    property boativar : string read Fboativar write Fboativar;
    property boexterno : string read Fboexterno write Fboexterno;
    property bopreencheratendente : string read Fbopreencheratendente write Fbopreencheratendente;
    [fk]
    property cdfuncaoatendente : integer read fcdfuncaoatendente write fcdfuncaoatendente;
    [fk]
    property cdfuncaotecnico : integer read fcdfuncaotecnico write fcdfuncaotecnico;
    [fk]
    property cdfuncaovendedor : integer read fcdfuncaovendedor write fcdfuncaovendedor;
    property bonuano : String read fbonuano write fbonuano;
    property bocor : String read fbocor write fbocor;
    property boprioridade : String read fboprioridade write fboprioridade;
    property bonukm : String read fbonukm write fbonukm;
    property bonubateria : String read fbonubateria write fbonubateria;
    property bodtaprovacao : String read fbodtaprovacao write fbodtaprovacao;
    property bohraprovacao : String read fbohraprovacao write fbohraprovacao;
    property bodtprevorcamento : String read fbodtprevorcamento write fbodtprevorcamento;
    property bohrprevorcamento : String read fbohrprevorcamento write fbohrprevorcamento;
    property boprevorcamentoobrigatorio : String read fboprevorcamentoobrigatorio write fboprevorcamentoobrigatorio;
    property bodtpreventrega: String read fbodtpreventrega write fbodtpreventrega;
    property bohrpreventrega : String read fbohrpreventrega write fbohrpreventrega;
    property bopreventregaobrigatorio : String read fbopreventregaobrigatorio write fbopreventregaobrigatorio;
    property bogarantia : String read fbogarantia write fbogarantia;
    property boprodutoexibircdalternativo : String read fboprodutoexibircdalternativo write fboprodutoexibircdalternativo;
    property boequipamentoguia : String read fboequipamentoguia write fboequipamentoguia;
    property bodigitarproduto : String read fbodigitarproduto write fbodigitarproduto;
    property boreportentregasemcomprovante : String read fboreportentregasemcomprovante write fboreportentregasemcomprovante;
    property bocomissaovendedor : String read fbocomissaovendedor write fbocomissaovendedor;
    property bocomissaotecnico : String read fbocomissaotecnico write fbocomissaotecnico;
    property bocomissaoorcado : String read fbocomissaoorcado write fbocomissaoorcado;
    property boassinaturadesconto : String read fboassinaturadesconto write fboassinaturadesconto;
    property bocomissaoorcadoproduto : String read fbocomissaoorcadoproduto write fbocomissaoorcadoproduto;
    property bocomissaoorcadoservico : String read fbocomissaoorcadoservico write fbocomissaoorcadoservico;
    property boetapa : String read fboetapa write fboetapa;
    property bocomissaoatendente : String read fbocomissaoatendente write fbocomissaoatendente;
    property borevisao : String read fborevisao write fborevisao;
    property bocomissaoatendenteproduto : String read fbocomissaoatendenteproduto write fbocomissaoatendenteproduto;
    property bocomissaotecnicoproduto : String read fbocomissaotecnicoproduto write fbocomissaotecnicoproduto;
    property bocomissaovendedorproduto : String read fbocomissaovendedorproduto write fbocomissaovendedorproduto;
    property bocomissaoatendenteservico : String read fbocomissaoatendenteservico write fbocomissaoatendenteservico;
    property boidentificadorcomissaoproduto : String read fboidentificadorcomissaoproduto write fboidentificadorcomissaoproduto;
    property bocomissaotecnicoservico : String read fbocomissaotecnicoservico write fbocomissaotecnicoservico;
    property bocomissaovendedorservico : String read fbocomissaovendedorservico write fbocomissaovendedorservico;
    property boreportorcamento : String read fboreportorcamento write fboreportorcamento;
    property nugerarcodigo : integer read fnugerarcodigo write fnugerarcodigo;
    property boequipamentolocal : String read fboequipamentolocal write fboequipamentolocal;
    property boqtdequipamentoobrigatorio : String read fboqtdequipamentoobrigatorio write fboqtdequipamentoobrigatorio;
    property bovendedorobrigatorio : String read fbovendedorobrigatorio write fbovendedorobrigatorio;
    property boatendenteobrigatorio : String read fboatendenteobrigatorio write fboatendenteobrigatorio;
    property botecnicoobrigatorio : String read fbotecnicoobrigatorio write fbotecnicoobrigatorio;
    property boqtdequipamento : String read fboqtdequipamento write fboqtdequipamento;
    property bogradeprodutolocalizacao : String read fbogradeprodutolocalizacao write fbogradeprodutolocalizacao;
    property boprodutoobrigatorio : String read fboprodutoobrigatorio write fboprodutoobrigatorio;
    property boprodutoinsercaoobrigatorio : String read fboprodutoinsercaoobrigatorio write fboprodutoinsercaoobrigatorio;
    property bonupatrimonio : String read fbonupatrimonio write fbonupatrimonio;
    property boentrada : String read fboentrada write fboentrada;
    property bosaida : String read fbosaida write fbosaida;
    property bodevolucaosemconserto : String read fbodevolucaosemconserto write fbodevolucaosemconserto;
    property borepresentante : String read fborepresentante write fborepresentante;
    property bocliente : String read fbocliente write fbocliente;
    property boalterarvalor : String read fboalterarvalor write fboalterarvalor;
    property botpgrade : String read fbotpgrade write fbotpgrade;
    property boservicoexterno : String read fboservicoexterno write fboservicoexterno;
    property boproduto : String read fboproduto write fboproduto;
    property boprodutoinsercao : String read fboprodutoinsercao write fboprodutoinsercao;
    property boacessorio : String read fboacessorio write fboacessorio;
    property bodefapr : String read fbodefapr write fbodefapr;
    property bodefenc : String read fbodefenc write fbodefenc;
    property boobservacao : String read fboobservacao write fboobservacao;
    property bosolucao : String read fbosolucao write fbosolucao;
    property boobservacaoanterior : String read fboobservacaoanterior write fboobservacaoanterior;
    property boobservacaotpordserv : String read fboobservacaotpordserv write fboobservacaotpordserv;
    property boobsinterna : String read fboobsinterna write fboobsinterna;
    property bosolinterna : String read fbosolinterna write fbosolinterna;
    property boosanterior : String read fboosanterior write fboosanterior;
    property boservico : String read fboservico write fboservico;
    property bopeca : String read fbopeca write fbopeca;
    property bofoto : String read fbofoto write fbofoto;
    property bodesenho : String read fbodesenho write fbodesenho;
    property bogeral : String read fbogeral write fbogeral;
    property bopintura : String read fbopintura write fbopintura;
    property boteste : String read fboteste write fboteste;
    property bodefeito : String read fbodefeito write fbodefeito;
    property boavaliacaotecnica : String read fboavaliacaotecnica write fboavaliacaotecnica;
    property boequipamento : String read fboequipamento write fboequipamento;
    property boequipamentoobrigatorio: String read fboequipamentoobrigatorio write fboequipamentoobrigatorio;
    property boatendente : String read fboatendente write fboatendente;
    property botecnico : String read fbotecnico write fbotecnico;
    property bovendedor : String read fbovendedor write fbovendedor;
    property bonukmobrigatorio : String read fbonukmobrigatorio write fbonukmobrigatorio;
    property boreportabertura : String read fboreportabertura write fboreportabertura;
    property boreportaberturasalvar : String read Fboreportaberturasalvar write fboreportaberturasalvar;
    property boreportentrega : String read fboreportentrega write fboreportentrega;
    property boreportacompanhamento: String read fboreportacompanhamento write fboreportacompanhamento;
    property boreportorcamentocontrato : String read fboreportorcamentocontrato write fboreportorcamentocontrato;
    property boreportorcamentoavulso : String read fboreportorcamentoavulso write fboreportorcamentoavulso;
    property bobaixaestoque : String read fbobaixaestoque write fbobaixaestoque;
    property bodtentradadigitar : String read fbodtentradadigitar write fbodtentradadigitar;
    property bohrentradadigitar : String read fbohrentradadigitar write fbohrentradadigitar;
    property bodtsaidadigitar : String read fbodtsaidadigitar write fbodtsaidadigitar;
    property botpvoltagem : String read fbotpvoltagem write fbotpvoltagem;
    property botpvoltagemobrigatorio : String read fbotpvoltagemobrigatorio write fbotpvoltagemobrigatorio;
    property cdstordserventrega : integer read Fcdstordserventrega write fcdstordserventrega;
    property bolocalservico : String read Fbolocalservico write Fbolocalservico;
    property bolacrebalanca : String read Fbolacrebalanca write Fbolacrebalanca;
    property boselobalanca : String read Fboselobalanca write Fboselobalanca;
    property bonuserieobrigatorio: string read fbonuserieobrigatorio write fbonuserieobrigatorio;
    property bonupatrimonioobrigatorio: string read fbonupatrimonioobrigatorio write fbonupatrimonioobrigatorio;
  end;

implementation

end.
